

import java.awt.Dimension;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 21nic
 */
public class AdditionalContact extends javax.swing.JFrame {

    /**
     * Creates new form AdditionalContact
     */
    public AdditionalContact() {
        initComponents();
        this.setMinimumSize(new Dimension(968, 749));
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrContact = new javax.swing.JScrollPane();
        txaContact = new javax.swing.JTextArea();
        pnlHeading = new javax.swing.JPanel();
        lblHeading = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        scrTechContact = new javax.swing.JScrollPane();
        txaTechContact = new javax.swing.JTextArea();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        txaContact.setEditable(false);
        txaContact.setBackground(new java.awt.Color(0, 102, 153));
        txaContact.setColumns(20);
        txaContact.setFont(new java.awt.Font("Monospaced", 1, 15)); // NOI18N
        txaContact.setForeground(new java.awt.Color(255, 255, 255));
        txaContact.setLineWrap(true);
        txaContact.setRows(5);
        txaContact.setText("Company Email Address: \nalliance@gmail.com\n\nTech Support Email Address: \nalliancetech@isat.co.za\n\nMain Office Telephone Number\n011 646 2122");
        scrContact.setViewportView(txaContact);

        getContentPane().add(scrContact);
        scrContact.setBounds(10, 290, 340, 230);

        pnlHeading.setBackground(new java.awt.Color(0, 102, 153));

        lblHeading.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        lblHeading.setForeground(new java.awt.Color(239, 128, 47));
        lblHeading.setText("Additional Contact Information");

        lblMinimize.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        lblMinimize.setForeground(new java.awt.Color(255, 255, 255));
        lblMinimize.setText("-");
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
        });

        lblExit.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblExit.setForeground(new java.awt.Color(255, 255, 255));
        lblExit.setText("x");
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlHeadingLayout = new javax.swing.GroupLayout(pnlHeading);
        pnlHeading.setLayout(pnlHeadingLayout);
        pnlHeadingLayout.setHorizontalGroup(
            pnlHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeadingLayout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(lblHeading)
                .addGap(140, 140, 140)
                .addComponent(lblMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlHeadingLayout.setVerticalGroup(
            pnlHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeadingLayout.createSequentialGroup()
                .addGroup(pnlHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeadingLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(lblHeading)
                .addGap(51, 51, 51))
        );

        getContentPane().add(pnlHeading);
        pnlHeading.setBounds(0, 0, 970, 150);

        txaTechContact.setEditable(false);
        txaTechContact.setBackground(new java.awt.Color(0, 102, 153));
        txaTechContact.setColumns(20);
        txaTechContact.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        txaTechContact.setForeground(new java.awt.Color(255, 255, 255));
        txaTechContact.setLineWrap(true);
        txaTechContact.setRows(5);
        txaTechContact.setText(" \n Tech Support Telephone Number: \n 011 646 1828\n\n Delivery Team Head Email Address: \n alliancedelivery@mweb.co.za\n\n Facebook & Instagram accounts: \n TennisAllianceSA\n");
        scrTechContact.setViewportView(txaTechContact);

        getContentPane().add(scrTechContact);
        scrTechContact.setBounds(650, 290, 310, 240);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesForPAT/thiem.jpg"))); // NOI18N
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 140, 970, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        this.setState(JFrame.ICONIFIED);//minimizes the screen
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        

        dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_lblExitMouseClicked

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JPanel pnlHeading;
    private javax.swing.JScrollPane scrContact;
    private javax.swing.JScrollPane scrTechContact;
    private javax.swing.JTextArea txaContact;
    private javax.swing.JTextArea txaTechContact;
    // End of variables declaration//GEN-END:variables
}
