
import java.awt.Dimension;

import java.sql.SQLException;


import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 21nic
 */
public class AdminSignIn extends javax.swing.JFrame {
public TennisAlliance dbObjTennis;
public String email;
   public AdminSignIn(){
       this.email = email;
       initComponents();
       this.setMinimumSize(new Dimension(869, 669));
       dbObjTennis = new TennisAlliance(email);
       this.setLocationRelativeTo(null);
   }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeading = new javax.swing.JPanel();
        lblAdminSignIn = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        btnSignIn = new javax.swing.JButton();
        lblCompulsoryEmail = new javax.swing.JLabel();
        lblEnterPasword = new javax.swing.JLabel();
        lblCompulsoryPassword = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEnterAdminEmail = new javax.swing.JTextField();
        pwdEnterAdminPass = new javax.swing.JPasswordField();
        lblErrorAdminEmail = new javax.swing.JLabel();
        lblErrorAdminPass = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHeading.setBackground(new java.awt.Color(0, 102, 153));

        lblAdminSignIn.setFont(new java.awt.Font("Rockwell", 1, 48)); // NOI18N
        lblAdminSignIn.setForeground(new java.awt.Color(239, 128, 47));
        lblAdminSignIn.setText("Admin Sign In");

        lblMinimize.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        lblMinimize.setForeground(new java.awt.Color(255, 255, 255));
        lblMinimize.setText("-");
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
        });

        lblExit.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblExit.setForeground(new java.awt.Color(255, 255, 255));
        lblExit.setText("x");
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlHeadingLayout = new javax.swing.GroupLayout(pnlHeading);
        pnlHeading.setLayout(pnlHeadingLayout);
        pnlHeadingLayout.setHorizontalGroup(
            pnlHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeadingLayout.createSequentialGroup()
                .addContainerGap(271, Short.MAX_VALUE)
                .addComponent(lblAdminSignIn)
                .addGap(180, 180, 180)
                .addComponent(lblMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlHeadingLayout.setVerticalGroup(
            pnlHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeadingLayout.createSequentialGroup()
                .addGroup(pnlHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 72, Short.MAX_VALUE))
            .addGroup(pnlHeadingLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblAdminSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, -1));

        btnSignIn.setBackground(new java.awt.Color(239, 128, 47));
        btnSignIn.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnSignIn.setForeground(new java.awt.Color(0, 102, 153));
        btnSignIn.setText("Sign In");
        btnSignIn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(239, 128, 47), new java.awt.Color(0, 102, 153), new java.awt.Color(239, 128, 47), new java.awt.Color(0, 102, 153)));
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInActionPerformed(evt);
            }
        });
        getContentPane().add(btnSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 260, 70));

        lblCompulsoryEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCompulsoryEmail.setForeground(new java.awt.Color(255, 51, 51));
        lblCompulsoryEmail.setText("*");
        getContentPane().add(lblCompulsoryEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 18, -1));

        lblEnterPasword.setBackground(new java.awt.Color(0, 102, 255));
        lblEnterPasword.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblEnterPasword.setForeground(new java.awt.Color(255, 255, 255));
        lblEnterPasword.setText("Enter Password");
        getContentPane().add(lblEnterPasword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, 30));

        lblCompulsoryPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCompulsoryPassword.setForeground(new java.awt.Color(255, 51, 51));
        lblCompulsoryPassword.setText("*");
        getContentPane().add(lblCompulsoryPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 18, -1));

        lblEmail.setBackground(new java.awt.Color(0, 102, 255));
        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Enter Admin Email Address");
        getContentPane().add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, 30));

        txtEnterAdminEmail.setBackground(new java.awt.Color(0, 102, 153));
        txtEnterAdminEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEnterAdminEmail.setPreferredSize(new java.awt.Dimension(300, 30));
        getContentPane().add(txtEnterAdminEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 225, -1));

        pwdEnterAdminPass.setBackground(new java.awt.Color(0, 102, 153));
        pwdEnterAdminPass.setForeground(new java.awt.Color(255, 255, 255));
        pwdEnterAdminPass.setMinimumSize(new java.awt.Dimension(130, 30));
        pwdEnterAdminPass.setPreferredSize(new java.awt.Dimension(130, 30));
        getContentPane().add(pwdEnterAdminPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 220, -1));

        lblErrorAdminEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblErrorAdminEmail.setForeground(new java.awt.Color(255, 204, 0));
        getContentPane().add(lblErrorAdminEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 510, 30));

        lblErrorAdminPass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblErrorAdminPass.setForeground(new java.awt.Color(255, 204, 0));
        getContentPane().add(lblErrorAdminPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 480, 30));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesForPAT/tsisti.jpg"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 870, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        this.setState(JFrame.ICONIFIED);//minimizes the screen
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        

        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_lblExitMouseClicked

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInActionPerformed

          String email = txtEnterAdminEmail.getText(); //getting the text from the text field and storing the value as a string
        String password = pwdEnterAdminPass.getText(); ////getting the text from the text field and storing the value as a string

           

        boolean flag = true;//boolean will be used to check if the substring is letters only 
        if (email.isEmpty()) {// presence check to see if a field has been left blank.
            lblErrorAdminEmail.setText("*ERROR: This field cannot be left blank.");//error message for presence check 
        } else {
            if ((email.length() < 6)) {//if the length is <6
                lblErrorAdminEmail.setText("*ERROR: Your email address cannnot be less than 6 characters in length.");
            } else {

                for (int i = 0; i < email.length(); i++) {//looping until the length of the name 
                    // checks to see if the character isnt a letter
                    if (!Character.isLetterOrDigit(email.charAt(i))) {//if the character is not a letter or then flag is false
                        flag = false;
                    }
                }
                int length = email.length();
                int count = 0;
                boolean checkAt = false;

                for (int i = 0; i < length; i++) {
                    if ((email.charAt(i)) == '@') {
                        count++;
                        checkAt = true;
                    }

                }
                if (count > 1) {
                   lblErrorAdminEmail.setText("*ERROR: Your email address cannot have more than 1 @");
                } else {
                    if (count == 0) {
                        lblErrorAdminEmail.setText("*ERROR: Your email address must have an @ in it!");
                    } else {
                        if (count == 1 && checkAt) {
                            lblErrorAdminEmail.setText("");
                        }
                    }

                }

            }

        }

        if (password.isEmpty()) {//presence check to see if a field has been left blank.

            lblErrorAdminPass.setText("*ERROR: This field cannot be left blank.");    //error messgae occurs if field has been left blank
        } 
        else{
            lblErrorAdminPass.setText("");
        }
        
        if (lblErrorAdminEmail.getText().equals("") && lblErrorAdminPass.getText().equals(""))
        try{
            dbObjTennis.checkDBAdmin(email, password);
          
            
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_btnSignInActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignIn;
    private javax.swing.JLabel lblAdminSignIn;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblCompulsoryEmail;
    private javax.swing.JLabel lblCompulsoryPassword;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEnterPasword;
    private javax.swing.JLabel lblErrorAdminEmail;
    private javax.swing.JLabel lblErrorAdminPass;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JPanel pnlHeading;
    private javax.swing.JPasswordField pwdEnterAdminPass;
    private javax.swing.JTextField txtEnterAdminEmail;
    // End of variables declaration//GEN-END:variables
}
