
import java.sql.SQLException;

import javax.swing.table.DefaultTableModel;
import javax.swing.*;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author 21nic
 */
public class BagsInfoAdmin extends javax.swing.JFrame {

    /**
     * Creates new form RacketsInfo
     */
    public TennisAlliance dbEquipObj;
    
    public String email;
 
    public BagsInfoAdmin(String Email) {
        this.email = email;
        initComponents();
        dbEquipObj = new TennisAlliance(email);
        dbEquipObj.showBagsAlphabetical(tblDisplayBags);
         this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrDisplayBags = new javax.swing.JScrollPane();
        tblDisplayBags = new javax.swing.JTable();
        pnlHeading = new javax.swing.JPanel();
        lblBagsPage = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        lblSearch = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtColour = new javax.swing.JTextField();
        lblColour = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnNewRecord = new javax.swing.JButton();
        txtRacketSpace = new javax.swing.JTextField();
        lblRacketSpace = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        lblPrice = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        lblstock = new javax.swing.JLabel();
        lblEnterUpdate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblDisplayBags.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblDisplayBags.setForeground(new java.awt.Color(239, 128, 47));
        tblDisplayBags.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BagName", "BagColour", "RacketSpace", "BagPrice(Rands)", "AvailableStock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDisplayBags.getTableHeader().setReorderingAllowed(false);
        scrDisplayBags.setViewportView(tblDisplayBags);
        if (tblDisplayBags.getColumnModel().getColumnCount() > 0) {
            tblDisplayBags.getColumnModel().getColumn(0).setResizable(false);
            tblDisplayBags.getColumnModel().getColumn(0).setPreferredWidth(180);
            tblDisplayBags.getColumnModel().getColumn(1).setResizable(false);
            tblDisplayBags.getColumnModel().getColumn(2).setResizable(false);
            tblDisplayBags.getColumnModel().getColumn(3).setResizable(false);
            tblDisplayBags.getColumnModel().getColumn(4).setResizable(false);
        }

        pnlHeading.setBackground(new java.awt.Color(0, 102, 153));

        lblBagsPage.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblBagsPage.setForeground(new java.awt.Color(239, 128, 47));
        lblBagsPage.setText("Bags Admin Page");

        lblMinimize.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        lblMinimize.setForeground(new java.awt.Color(255, 255, 255));
        lblMinimize.setText("-");
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
        });

        lblExit.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblExit.setForeground(new java.awt.Color(255, 255, 255));
        lblExit.setText("x");
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlHeadingLayout = new javax.swing.GroupLayout(pnlHeading);
        pnlHeading.setLayout(pnlHeadingLayout);
        pnlHeadingLayout.setHorizontalGroup(
            pnlHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeadingLayout.createSequentialGroup()
                .addGap(721, 721, 721)
                .addComponent(lblBagsPage, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 642, Short.MAX_VALUE)
                .addComponent(lblMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlHeadingLayout.setVerticalGroup(
            pnlHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeadingLayout.createSequentialGroup()
                .addGroup(pnlHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlHeadingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBagsPage, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
        });

        lblSearch.setText("Search for Bags");

        btnDelete.setText("Delete Selected Record");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });

        txtName.setMinimumSize(new java.awt.Dimension(8, 20));
        txtName.setPreferredSize(new java.awt.Dimension(100, 30));

        lblName.setText("Bag Name");

        txtColour.setMinimumSize(new java.awt.Dimension(8, 20));
        txtColour.setPreferredSize(new java.awt.Dimension(100, 30));

        lblColour.setText("Bag colour");

        btnUpdate.setText("Update");
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });

        btnNewRecord.setText("Create New Record");
        btnNewRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewRecordMouseClicked(evt);
            }
        });

        txtRacketSpace.setMinimumSize(new java.awt.Dimension(8, 20));
        txtRacketSpace.setPreferredSize(new java.awt.Dimension(100, 30));

        lblRacketSpace.setText("Racket Space");

        txtPrice.setMinimumSize(new java.awt.Dimension(8, 20));
        txtPrice.setPreferredSize(new java.awt.Dimension(100, 30));

        lblPrice.setText("Bag Price(Rands)");

        txtStock.setMinimumSize(new java.awt.Dimension(8, 20));
        txtStock.setPreferredSize(new java.awt.Dimension(100, 30));

        lblstock.setText("Available Stock");

        lblEnterUpdate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEnterUpdate.setForeground(new java.awt.Color(51, 0, 255));
        lblEnterUpdate.setText("Enter New values to update Selected field");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSearch)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrDisplayBags, javax.swing.GroupLayout.PREFERRED_SIZE, 1684, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(pnlHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblName)
                                .addGap(113, 113, 113))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblColour)
                            .addComponent(txtColour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRacketSpace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRacketSpace))
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrice)
                            .addComponent(txtPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblstock)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDelete)
                        .addGap(270, 270, 270)
                        .addComponent(lblEnterUpdate))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(581, 581, 581)
                        .addComponent(btnUpdate)
                        .addGap(41, 41, 41)
                        .addComponent(btnNewRecord)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHeading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(lblSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrDisplayBags, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEnterUpdate, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName)
                            .addComponent(lblColour))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtColour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRacketSpace)
                            .addComponent(lblPrice)
                            .addComponent(lblstock))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRacketSpace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnNewRecord))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        this.setState(JFrame.ICONIFIED);//minimizes the screen
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked

        this.dispose();
    }//GEN-LAST:event_lblExitMouseClicked

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
        String search = txtSearch.getText();
        
         

        DefaultTableModel model = (DefaultTableModel) tblDisplayBags.getModel();
        model.setRowCount(0);

        dbEquipObj.showBagsSearch(tblDisplayBags, search);//displaying search inside the table that was created to display the reuslts of the search
    }//GEN-LAST:event_txtSearchKeyPressed

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblDisplayBags.getModel();
        int columnBags = 0;
        int columnColour= 1;
        int row = tblDisplayBags.getSelectedRow();
        
        String tempOrderBags = tblDisplayBags.getModel().getValueAt(row, columnBags).toString();
        String tempOrderColour = tblDisplayBags.getModel().getValueAt(row, columnColour).toString();
        
        //updating where the ID is what they entered the ID to be
        try{//try catch here in order to try and catch the SQLExcepption error
            dbEquipObj.deleteBag(tempOrderBags, tempOrderColour);//this is used to update the record
            JOptionPane.showMessageDialog(null, "Item has been successfully removed!");
            model.setRowCount(0);
            DefaultTableModel modelRefreshed = (DefaultTableModel) tblDisplayBags.getModel();
            dbEquipObj.showBagsAlphabetical(tblDisplayBags);
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Record was not deleted " +e);

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblDisplayBags.getModel();
        int columnBags = 0;
        int columnColour = 1;
        int row = tblDisplayBags.getSelectedRow();
        
        String tempOrderBags = tblDisplayBags.getModel().getValueAt(row, columnBags).toString();
        String tempOrderColour = tblDisplayBags.getModel().getValueAt(row, columnColour).toString();

        String name = txtName.getText();
        
        String colour = txtColour.getText();
        int space  = Integer.parseInt(txtRacketSpace.getText());
        int price = Integer.parseInt(txtPrice.getText());
        int stock = Integer.parseInt(txtStock.getText());
        
        //updating where the ID is what they entered the ID to be
        try{//try catch here in order to try and catch the SQLExcepption error
            dbEquipObj.updateBag(tempOrderBags,tempOrderColour,colour, name, space, price, stock);//this is used to update the record
            JOptionPane.showMessageDialog(null, "Item has been successfully updated!");
            model.setRowCount(0);
            DefaultTableModel modelRefreshed = (DefaultTableModel) tblDisplayBags.getModel();
            dbEquipObj.showBagsAlphabetical(tblDisplayBags);
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Cannot insert record\n " +e);

        }
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void btnNewRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewRecordMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblDisplayBags.getModel();

        String name = txtName.getText();
        
        String colour = txtColour.getText();
        int space  = Integer.parseInt(txtRacketSpace.getText());
        int price = Integer.parseInt(txtPrice.getText());
        int stock = Integer.parseInt(txtStock.getText());
        
       
        try{//try catch here in order to try and catch the SQLExcepption error
            dbEquipObj.insertBag(name, colour, space, price, stock);//this is used to update the record
            JOptionPane.showMessageDialog(null, "New record has successfully been added to the database!");
            model.setRowCount(0);
            DefaultTableModel modelRefreshed = (DefaultTableModel) tblDisplayBags.getModel();
            dbEquipObj.showBagsAlphabetical(tblDisplayBags);

        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Cannot insert record\n " +e);

        }
    }//GEN-LAST:event_btnNewRecordMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNewRecord;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblBagsPage;
    private javax.swing.JLabel lblColour;
    private javax.swing.JLabel lblEnterUpdate;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblRacketSpace;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblstock;
    private javax.swing.JPanel pnlHeading;
    private javax.swing.JScrollPane scrDisplayBags;
    private javax.swing.JTable tblDisplayBags;
    private javax.swing.JTextField txtColour;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtRacketSpace;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
