
import java.sql.SQLException;

import javax.swing.table.DefaultTableModel;
import javax.swing.*;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author 21nic
 */
public class BagsInfo extends javax.swing.JFrame {

    /**
     * Creates new form RacketsInfo
     */
    public TennisAlliance dbObjTennis;
    
    public String email;
    private String password;
     public  String sqlSearchBags= "";
 public String resultsOfSearchBags= "";
 
    public BagsInfo(String email, String password) {
        this.email = email;
        this.password = password;
        initComponents();
        
        dbObjTennis = new TennisAlliance(email);
        dbObjTennis.showBagsAlphabetical(tblDisplayBags);
         this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgpFilterOptions = new javax.swing.ButtonGroup();
        scrDisplayBags = new javax.swing.JScrollPane();
        tblDisplayBags = new javax.swing.JTable();
        btnBigBags = new javax.swing.JRadioButton();
        btnPriceAsc = new javax.swing.JRadioButton();
        btnPriceDesc = new javax.swing.JRadioButton();
        btnAddToCart = new javax.swing.JButton();
        pnlHeading = new javax.swing.JPanel();
        lblFilters = new javax.swing.JLabel();
        lblBagsPage = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        btnMediumBags = new javax.swing.JRadioButton();
        btnSmallBags = new javax.swing.JRadioButton();
        btnWhite = new javax.swing.JRadioButton();
        btnBlack = new javax.swing.JRadioButton();
        btnRed = new javax.swing.JRadioButton();
        txtSearch = new javax.swing.JTextField();
        lblSearch = new javax.swing.JLabel();
        btnCheckout = new javax.swing.JButton();
        btnFaqPage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblDisplayBags.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblDisplayBags.setForeground(new java.awt.Color(239, 128, 47));
        tblDisplayBags.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BagName", "BagColour", "RacketSpace", "BagPrice(Rands)", "AvailableStock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDisplayBags.getTableHeader().setReorderingAllowed(false);
        scrDisplayBags.setViewportView(tblDisplayBags);
        if (tblDisplayBags.getColumnModel().getColumnCount() > 0) {
            tblDisplayBags.getColumnModel().getColumn(0).setResizable(false);
            tblDisplayBags.getColumnModel().getColumn(0).setPreferredWidth(180);
            tblDisplayBags.getColumnModel().getColumn(1).setResizable(false);
            tblDisplayBags.getColumnModel().getColumn(2).setResizable(false);
            tblDisplayBags.getColumnModel().getColumn(3).setResizable(false);
            tblDisplayBags.getColumnModel().getColumn(4).setResizable(false);
        }

        bgpFilterOptions.add(btnBigBags);
        btnBigBags.setText("Big Bags");
        btnBigBags.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBigBagsMouseClicked(evt);
            }
        });

        bgpFilterOptions.add(btnPriceAsc);
        btnPriceAsc.setText("Price Ascending");
        btnPriceAsc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPriceAscMouseClicked(evt);
            }
        });

        bgpFilterOptions.add(btnPriceDesc);
        btnPriceDesc.setText("Price Descending");
        btnPriceDesc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPriceDescMouseClicked(evt);
            }
        });

        btnAddToCart.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddToCart.setText("Add selected item to cart");
        btnAddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToCartActionPerformed(evt);
            }
        });

        pnlHeading.setBackground(new java.awt.Color(0, 102, 153));

        lblFilters.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblFilters.setForeground(new java.awt.Color(239, 128, 47));
        lblFilters.setText("Filters:");

        lblBagsPage.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblBagsPage.setForeground(new java.awt.Color(239, 128, 47));
        lblBagsPage.setText("Bags Page");

        lblMinimize.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        lblMinimize.setForeground(new java.awt.Color(255, 255, 255));
        lblMinimize.setText("-");
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
        });

        lblExit.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblExit.setForeground(new java.awt.Color(255, 255, 255));
        lblExit.setText("x");
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlHeadingLayout = new javax.swing.GroupLayout(pnlHeading);
        pnlHeading.setLayout(pnlHeadingLayout);
        pnlHeadingLayout.setHorizontalGroup(
            pnlHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeadingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFilters)
                .addGap(639, 639, 639)
                .addComponent(lblBagsPage, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 748, Short.MAX_VALUE)
                .addComponent(lblMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlHeadingLayout.setVerticalGroup(
            pnlHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeadingLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFilters)
                .addContainerGap())
            .addGroup(pnlHeadingLayout.createSequentialGroup()
                .addGroup(pnlHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlHeadingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBagsPage, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        bgpFilterOptions.add(btnMediumBags);
        btnMediumBags.setText("Medium Bags");
        btnMediumBags.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMediumBagsMouseClicked(evt);
            }
        });

        bgpFilterOptions.add(btnSmallBags);
        btnSmallBags.setText("Small Bags");
        btnSmallBags.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSmallBagsMouseClicked(evt);
            }
        });

        bgpFilterOptions.add(btnWhite);
        btnWhite.setForeground(new java.awt.Color(255, 255, 255));
        btnWhite.setText("Colour: White");
        btnWhite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnWhiteMouseClicked(evt);
            }
        });

        bgpFilterOptions.add(btnBlack);
        btnBlack.setText("Colour: Black");
        btnBlack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBlackMouseClicked(evt);
            }
        });

        bgpFilterOptions.add(btnRed);
        btnRed.setForeground(new java.awt.Color(204, 0, 0));
        btnRed.setText("Colour: Red");
        btnRed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRedMouseClicked(evt);
            }
        });

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
        });

        lblSearch.setText("Search for Bags by Bag Name");

        btnCheckout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCheckout.setText("Checkout");
        btnCheckout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCheckoutMouseClicked(evt);
            }
        });

        btnFaqPage.setText("FAQ");
        btnFaqPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFaqPageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPriceAsc)
                            .addComponent(btnPriceDesc)
                            .addComponent(btnBigBags)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnMediumBags))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSmallBags))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnWhite))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBlack))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRed))
                    .addComponent(lblSearch)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scrDisplayBags)
                .addContainerGap())
            .addComponent(pnlHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(btnFaqPage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddToCart)
                .addGap(386, 386, 386)
                .addComponent(btnCheckout)
                .addGap(284, 284, 284))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHeading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnPriceAsc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPriceDesc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBigBags)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMediumBags)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSmallBags)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnWhite)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBlack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRed)
                        .addGap(18, 18, 18)
                        .addComponent(lblSearch)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrDisplayBags, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFaqPage, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCheckout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(btnAddToCart, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPriceAscMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPriceAscMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblDisplayBags.getModel();
        model.setRowCount(0);

        dbObjTennis.showBagsPriceAsc(tblDisplayBags);
    }//GEN-LAST:event_btnPriceAscMouseClicked

    private void btnPriceDescMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPriceDescMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblDisplayBags.getModel();
        model.setRowCount(0);

        dbObjTennis.showBagsPriceDesc(tblDisplayBags);
    }//GEN-LAST:event_btnPriceDescMouseClicked

    private void btnBigBagsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBigBagsMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblDisplayBags.getModel();
        model.setRowCount(0);

        dbObjTennis.showBagsBig(tblDisplayBags);
    }//GEN-LAST:event_btnBigBagsMouseClicked

    private void btnAddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToCartActionPerformed
        TennisAlliance dbObjTennis = new TennisAlliance(email);
        DefaultTableModel model = (DefaultTableModel) tblDisplayBags.getModel();
        int columnBag = 0;
        int columnPrice = 3;
        int row = tblDisplayBags.getSelectedRow();
        String tempOrder = tblDisplayBags.getModel().getValueAt(row, columnBag).toString();

        String tempOrderPrice = tblDisplayBags.getModel().getValueAt(row, columnPrice).toString();
        String tempEmail = email;

        try {
            dbObjTennis.addOrder(tempEmail, tempOrder, tempOrderPrice);
            

            
        } catch (SQLException ex) {
           
        }

    }//GEN-LAST:event_btnAddToCartActionPerformed

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        this.setState(JFrame.ICONIFIED);//minimizes the screen
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked

        this.dispose();
    }//GEN-LAST:event_lblExitMouseClicked

    private void btnMediumBagsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMediumBagsMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblDisplayBags.getModel();
        model.setRowCount(0);

        dbObjTennis.showBagsMedium(tblDisplayBags);
    }//GEN-LAST:event_btnMediumBagsMouseClicked

    private void btnSmallBagsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSmallBagsMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblDisplayBags.getModel();
        model.setRowCount(0);

        dbObjTennis.showBagsSmall(tblDisplayBags);
    }//GEN-LAST:event_btnSmallBagsMouseClicked

    private void btnWhiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWhiteMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblDisplayBags.getModel();
        model.setRowCount(0);

        dbObjTennis.showBagsWhite(tblDisplayBags);
    }//GEN-LAST:event_btnWhiteMouseClicked

    private void btnBlackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBlackMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblDisplayBags.getModel();
        model.setRowCount(0);

        dbObjTennis.showBagsBlack(tblDisplayBags);
    }//GEN-LAST:event_btnBlackMouseClicked

    private void btnRedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRedMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblDisplayBags.getModel();
        model.setRowCount(0);

        dbObjTennis.showBagsRed(tblDisplayBags);         // TODO add your handling code here:
    }//GEN-LAST:event_btnRedMouseClicked

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
      String search = txtSearch.getText();
        
         

        DefaultTableModel model = (DefaultTableModel) tblDisplayBags.getModel();
        model.setRowCount(0);

        dbObjTennis.showBagsSearch(tblDisplayBags, search);//displaying search inside the table that was created to display the reuslts of the search
    }//GEN-LAST:event_txtSearchKeyPressed

    private void btnCheckoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckoutMouseClicked

        new CheckOutPage(email, password).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnCheckoutMouseClicked

    private void btnFaqPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFaqPageActionPerformed
        new FAQ().setVisible(true);
    }//GEN-LAST:event_btnFaqPageActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgpFilterOptions;
    private javax.swing.JButton btnAddToCart;
    private javax.swing.JRadioButton btnBigBags;
    private javax.swing.JRadioButton btnBlack;
    private javax.swing.JButton btnCheckout;
    private javax.swing.JButton btnFaqPage;
    private javax.swing.JRadioButton btnMediumBags;
    private javax.swing.JRadioButton btnPriceAsc;
    private javax.swing.JRadioButton btnPriceDesc;
    private javax.swing.JRadioButton btnRed;
    private javax.swing.JRadioButton btnSmallBags;
    private javax.swing.JRadioButton btnWhite;
    private javax.swing.JLabel lblBagsPage;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblFilters;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JPanel pnlHeading;
    private javax.swing.JScrollPane scrDisplayBags;
    private javax.swing.JTable tblDisplayBags;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
