
import java.sql.SQLException;

import javax.swing.table.DefaultTableModel;
import javax.swing.*;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author 21nic
 */
public class BallsInfoAdmin extends javax.swing.JFrame {

    /**
     * Creates new form RacketsInfo
     */
    public TennisAlliance dbEquipObj;
   
    public String email;
     

    public BallsInfoAdmin(String Email) {
        this.email = email;
        initComponents();
        dbEquipObj = new TennisAlliance(email);
        dbEquipObj.showBallsAlphabetical(tblDisplayBalls);
         this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdBgpFilterOptions = new javax.swing.ButtonGroup();
        scrDisplayRackets = new javax.swing.JScrollPane();
        tblDisplayBalls = new javax.swing.JTable();
        pnlHeading = new javax.swing.JPanel();
        lblBallsAdminPage = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        lblSearch = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        lblBallName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblEnterUpdate = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnNewRecord = new javax.swing.JButton();
        lblBallPrice = new javax.swing.JLabel();
        txtCanPrice = new javax.swing.JTextField();
        lblstock = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        chkHighAlt = new javax.swing.JCheckBox();
        txtBallCol = new javax.swing.JTextField();
        lblStringColour = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblDisplayBalls.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblDisplayBalls.setForeground(new java.awt.Color(239, 128, 47));
        tblDisplayBalls.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BallName", "HighAltitude", "CanColour", "PricePerCan(Rands)", "AvailableStock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Boolean.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDisplayBalls.getTableHeader().setReorderingAllowed(false);
        scrDisplayRackets.setViewportView(tblDisplayBalls);
        if (tblDisplayBalls.getColumnModel().getColumnCount() > 0) {
            tblDisplayBalls.getColumnModel().getColumn(0).setResizable(false);
            tblDisplayBalls.getColumnModel().getColumn(0).setPreferredWidth(180);
            tblDisplayBalls.getColumnModel().getColumn(1).setResizable(false);
            tblDisplayBalls.getColumnModel().getColumn(2).setResizable(false);
            tblDisplayBalls.getColumnModel().getColumn(3).setResizable(false);
            tblDisplayBalls.getColumnModel().getColumn(4).setResizable(false);
        }

        pnlHeading.setBackground(new java.awt.Color(0, 102, 153));

        lblBallsAdminPage.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblBallsAdminPage.setForeground(new java.awt.Color(239, 128, 47));
        lblBallsAdminPage.setText("Balls Admin Page");

        lblMinimize.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        lblMinimize.setForeground(new java.awt.Color(255, 255, 255));
        lblMinimize.setText("-");
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
        });

        lblExit.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblExit.setForeground(new java.awt.Color(255, 255, 255));
        lblExit.setText("x");
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlHeadingLayout = new javax.swing.GroupLayout(pnlHeading);
        pnlHeading.setLayout(pnlHeadingLayout);
        pnlHeadingLayout.setHorizontalGroup(
            pnlHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeadingLayout.createSequentialGroup()
                .addGap(709, 709, 709)
                .addComponent(lblBallsAdminPage, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 436, Short.MAX_VALUE)
                .addComponent(lblMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlHeadingLayout.setVerticalGroup(
            pnlHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeadingLayout.createSequentialGroup()
                .addGroup(pnlHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBallsAdminPage, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                .addGap(0, 21, Short.MAX_VALUE))
        );

        lblSearch.setText("Search for Ball");

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
        });

        btnDelete.setText("Delete Selected Record");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });

        lblBallName.setText("Ball Name");

        txtName.setPreferredSize(new java.awt.Dimension(100, 30));

        lblEnterUpdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEnterUpdate.setForeground(new java.awt.Color(51, 0, 255));
        lblEnterUpdate.setText("Enter New values to update Selected field");

        btnUpdate.setText("Update");
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });

        btnNewRecord.setText("Create New Record");
        btnNewRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewRecordMouseClicked(evt);
            }
        });

        lblBallPrice.setText("PricePerCan(Rands)");

        txtCanPrice.setPreferredSize(new java.awt.Dimension(100, 30));

        lblstock.setText("Available Stock");

        txtStock.setPreferredSize(new java.awt.Dimension(100, 30));

        chkHighAlt.setText("HighAltitude");

        txtBallCol.setPreferredSize(new java.awt.Dimension(100, 30));

        lblStringColour.setText("Ball colour");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(592, 592, 592)
                        .addComponent(lblEnterUpdate))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSearch)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(scrDisplayRackets, javax.swing.GroupLayout.PREFERRED_SIZE, 1313, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnDelete)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(384, 384, 384)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBallName)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(chkHighAlt)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblStringColour)
                                    .addComponent(txtBallCol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCanPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBallPrice))
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblstock)
                                    .addComponent(txtStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUpdate)
                                .addGap(41, 41, 41)
                                .addComponent(btnNewRecord)
                                .addGap(226, 226, 226)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHeading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(lblSearch)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrDisplayRackets, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(lblEnterUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBallPrice)
                    .addComponent(lblstock)
                    .addComponent(lblStringColour)
                    .addComponent(lblBallName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCanPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkHighAlt)
                    .addComponent(txtBallCol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnNewRecord))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        this.setState(JFrame.ICONIFIED);//minimizes the screen
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked

        this.dispose();
    }//GEN-LAST:event_lblExitMouseClicked

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
        String search = txtSearch.getText();
        //making the variable equal to the text/search that was entered by the user
      //where result is like the help type entered by user

        DefaultTableModel model = (DefaultTableModel) tblDisplayBalls.getModel();
        model.setRowCount(0);

        dbEquipObj.showBallsSearch(tblDisplayBalls, search);//displaying search inside the table that was created to display the reuslts of the search
    }//GEN-LAST:event_txtSearchKeyPressed

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblDisplayBalls.getModel();
        int columnBall = 0;
        int columnColour= 2;
        int row = tblDisplayBalls.getSelectedRow();
        
        String tempOrderBall = tblDisplayBalls.getModel().getValueAt(row, columnBall).toString();
        String tempOrderColour = tblDisplayBalls.getModel().getValueAt(row, columnColour).toString();
        
        //updating where the ID is what they entered the ID to be
        try{//try catch here in order to try and catch the SQLExcepption error
            dbEquipObj.deleteBall(tempOrderBall, tempOrderColour);//this is used to update the record
            JOptionPane.showMessageDialog(null, "Item has been successfully removed!");
            model.setRowCount(0);
            DefaultTableModel modelRefreshed = (DefaultTableModel) tblDisplayBalls.getModel();
            dbEquipObj.showBallsAlphabetical(tblDisplayBalls);
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Record was not deleted " +e);

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblDisplayBalls.getModel();
        int columnBall = 0;
        int columnColour = 2;
        int row = tblDisplayBalls.getSelectedRow();
        
        String tempOrderBall = tblDisplayBalls.getModel().getValueAt(row, columnBall).toString();
        String tempOrderColour = tblDisplayBalls.getModel().getValueAt(row, columnColour).toString();

        String name = txtName.getText();
       boolean highAlt = chkHighAlt.isSelected();
        String colour = txtBallCol.getText();
        int price = Integer.parseInt(txtCanPrice.getText());
        int stock = Integer.parseInt(txtStock.getText());
        
        //updating where the ID is what they entered the ID to be
        try{//try catch here in order to try and catch the SQLExcepption error
            dbEquipObj.updateBall(tempOrderBall, tempOrderColour, name, highAlt, colour, price, stock);//this is used to update the record
            JOptionPane.showMessageDialog(null, "Item has been successfully updated!");
            model.setRowCount(0);
            DefaultTableModel modelRefreshed = (DefaultTableModel) tblDisplayBalls.getModel();
            dbEquipObj.showBallsAlphabetical(tblDisplayBalls);
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Cannot insert record\n " +e);

        }
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void btnNewRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewRecordMouseClicked
         DefaultTableModel model = (DefaultTableModel) tblDisplayBalls.getModel();
       
        
      

        String name = txtName.getText();
       boolean highAlt = chkHighAlt.isSelected();
        String colour = txtBallCol.getText();
        int price = Integer.parseInt(txtCanPrice.getText());
        int stock = Integer.parseInt(txtStock.getText());
        
        //updating where the ID is what they entered the ID to be
        try{//try catch here in order to try and catch the SQLExcepption error
            dbEquipObj.insertBall(name, highAlt, colour, price, stock);//this is used to update the record
            JOptionPane.showMessageDialog(null, "Item has been successfully updated!");
            model.setRowCount(0);
            DefaultTableModel modelRefreshed = (DefaultTableModel) tblDisplayBalls.getModel();
            dbEquipObj.showBallsAlphabetical(tblDisplayBalls);
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Cannot insert record\n " +e);

        }
    }//GEN-LAST:event_btnNewRecordMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNewRecord;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox chkHighAlt;
    private javax.swing.JLabel lblBallName;
    private javax.swing.JLabel lblBallPrice;
    private javax.swing.JLabel lblBallsAdminPage;
    private javax.swing.JLabel lblEnterUpdate;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblStringColour;
    private javax.swing.JLabel lblstock;
    private javax.swing.JPanel pnlHeading;
    private javax.swing.ButtonGroup rdBgpFilterOptions;
    private javax.swing.JScrollPane scrDisplayRackets;
    private javax.swing.JTable tblDisplayBalls;
    private javax.swing.JTextField txtBallCol;
    private javax.swing.JTextField txtCanPrice;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
