
import java.sql.SQLException;

import javax.swing.table.DefaultTableModel;
import javax.swing.*;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author 21nic
 */
public class CapsInfoAdmin extends javax.swing.JFrame {

    /**
     * Creates new form RacketsInfo
     */
    public TennisAlliance dbObjTennis;
   
    public String email;
  
    public CapsInfoAdmin(String Email) {
        this.email = email;
        initComponents();
        dbObjTennis = new TennisAlliance(email);
        dbObjTennis.showCapsAlphabetical(tblDisplayCaps);
         this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdBgpFilterOptions = new javax.swing.ButtonGroup();
        scrDisplayCaps = new javax.swing.JScrollPane();
        tblDisplayCaps = new javax.swing.JTable();
        pnlHeading = new javax.swing.JPanel();
        lblCapsPage = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        lblSearch = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtColour = new javax.swing.JTextField();
        lblColour = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnNewRecord = new javax.swing.JButton();
        txtPrice = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        lblstock = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblEnterUpdate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblDisplayCaps.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblDisplayCaps.setForeground(new java.awt.Color(239, 128, 47));
        tblDisplayCaps.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cap Name", "Cap Colour", "Cap Price", "Available Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDisplayCaps.getTableHeader().setReorderingAllowed(false);
        scrDisplayCaps.setViewportView(tblDisplayCaps);
        if (tblDisplayCaps.getColumnModel().getColumnCount() > 0) {
            tblDisplayCaps.getColumnModel().getColumn(0).setResizable(false);
            tblDisplayCaps.getColumnModel().getColumn(0).setPreferredWidth(180);
            tblDisplayCaps.getColumnModel().getColumn(1).setResizable(false);
            tblDisplayCaps.getColumnModel().getColumn(2).setResizable(false);
            tblDisplayCaps.getColumnModel().getColumn(3).setResizable(false);
        }

        pnlHeading.setBackground(new java.awt.Color(0, 102, 153));

        lblCapsPage.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblCapsPage.setForeground(new java.awt.Color(239, 128, 47));
        lblCapsPage.setText("Caps Admin Page");

        lblMinimize.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        lblMinimize.setForeground(new java.awt.Color(255, 255, 255));
        lblMinimize.setText("-");
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
        });

        lblExit.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblExit.setForeground(new java.awt.Color(255, 255, 255));
        lblExit.setText("x");
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlHeadingLayout = new javax.swing.GroupLayout(pnlHeading);
        pnlHeading.setLayout(pnlHeadingLayout);
        pnlHeadingLayout.setHorizontalGroup(
            pnlHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeadingLayout.createSequentialGroup()
                .addGap(721, 721, 721)
                .addComponent(lblCapsPage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 695, Short.MAX_VALUE)
                .addComponent(lblMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlHeadingLayout.setVerticalGroup(
            pnlHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeadingLayout.createSequentialGroup()
                .addGroup(pnlHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlHeadingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCapsPage, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        lblSearch.setText("Search for Cap");

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
        });

        btnDelete.setText("Delete Selected Record");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });

        txtName.setPreferredSize(new java.awt.Dimension(100, 30));

        lblName.setText("Cap Name");

        txtColour.setPreferredSize(new java.awt.Dimension(100, 30));

        lblColour.setText("Cap colour");

        btnUpdate.setText("Update");
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });

        btnNewRecord.setText("Create New Record");
        btnNewRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewRecordMouseClicked(evt);
            }
        });

        txtPrice.setPreferredSize(new java.awt.Dimension(100, 30));

        txtStock.setPreferredSize(new java.awt.Dimension(100, 30));

        lblstock.setText("Available Stock");

        lblPrice.setText("Cap Price(Rands)");

        lblEnterUpdate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEnterUpdate.setForeground(new java.awt.Color(51, 0, 255));
        lblEnterUpdate.setText("Enter New values to update Selected field");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(324, 324, 324)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblName)
                            .addGap(113, 113, 113))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(61, 61, 61)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnDelete)
                        .addGap(192, 192, 192)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblColour)
                            .addComponent(txtColour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrice)
                            .addComponent(txtPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblstock)))
                    .addComponent(lblEnterUpdate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(722, 722, 722)
                        .addComponent(btnUpdate)
                        .addGap(41, 41, 41)
                        .addComponent(btnNewRecord))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSearch)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(scrDisplayCaps)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHeading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(scrDisplayCaps, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEnterUpdate)
                            .addComponent(btnDelete))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblName)
                                    .addComponent(lblColour))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtColour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPrice)
                                    .addComponent(lblstock))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUpdate)
                            .addComponent(btnNewRecord))
                        .addGap(52, 52, 52))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSearch)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        this.setState(JFrame.ICONIFIED);//minimizes the screen
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked

        this.dispose();
    }//GEN-LAST:event_lblExitMouseClicked

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
        String search = txtSearch.getText();
        //making the variable equal to the text/search that was entered by the user
      //where result is like the help type entered by user

        DefaultTableModel model = (DefaultTableModel) tblDisplayCaps.getModel();
        model.setRowCount(0);

        dbObjTennis.showCapsSearch(tblDisplayCaps, search);//displaying search inside the table that was created to display the reuslts of the search
    }//GEN-LAST:event_txtSearchKeyPressed

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblDisplayCaps.getModel();
        int columnCaps = 0;
        int columnColour= 1;
        int row = tblDisplayCaps.getSelectedRow();

        String tempOrderCaps = tblDisplayCaps.getModel().getValueAt(row, columnCaps).toString();
        String tempOrderColour = tblDisplayCaps.getModel().getValueAt(row, columnColour).toString();
       
        //updating where the ID is what they entered the ID to be
        try{//try catch here in order to try and catch the SQLExcepption error
            dbObjTennis.deleteCap(tempOrderCaps, tempOrderColour);//this is used to update the record
            JOptionPane.showMessageDialog(null, "Item has been successfully removed!");
            model.setRowCount(0);
            DefaultTableModel modelRefreshed = (DefaultTableModel) tblDisplayCaps.getModel();
            dbObjTennis.showCapsAlphabetical(tblDisplayCaps);
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Record was not deleted " +e);

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblDisplayCaps.getModel();
        int columnCaps = 0;
        int columnColour = 1;
        int row = tblDisplayCaps.getSelectedRow();

        String tempOrderCaps = tblDisplayCaps.getModel().getValueAt(row, columnCaps).toString();
        String tempOrderColour = tblDisplayCaps.getModel().getValueAt(row, columnColour).toString();

        String name = txtName.getText();
        String colour = txtColour.getText();
        int price = Integer.parseInt(txtPrice.getText());
        int stock = Integer.parseInt(txtStock.getText());
        
     
        //updating where the ID is what they entered the ID to be
        try{//try catch here in order to try and catch the SQLExcepption error
            dbObjTennis.updateCap(tempOrderCaps, tempOrderColour, name, colour, price, stock);//this is used to update the record
            JOptionPane.showMessageDialog(null, "Item has been successfully updated!");
            model.setRowCount(0);
            DefaultTableModel modelRefreshed = (DefaultTableModel) tblDisplayCaps.getModel();
            dbObjTennis.showCapsAlphabetical(tblDisplayCaps);
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Cannot insert record\n " +e);

        }
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void btnNewRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewRecordMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblDisplayCaps.getModel();

        String name = txtName.getText();
        String colour = txtColour.getText();
        int price = Integer.parseInt(txtPrice.getText());
        int stock = Integer.parseInt(txtStock.getText());
        
        //updating where the ID is what they entered the ID to be
        try{//try catch here in order to try and catch the SQLExcepption error
            dbObjTennis.insertCap(name, colour, price, stock);//this is used to update the record
            JOptionPane.showMessageDialog(null, "New record has successfully been added to the database!");
            model.setRowCount(0);
            DefaultTableModel modelRefreshed = (DefaultTableModel) tblDisplayCaps.getModel();
            dbObjTennis.showCapsAlphabetical(tblDisplayCaps);

        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Cannot insert record\n " +e);

        }
    }//GEN-LAST:event_btnNewRecordMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNewRecord;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblCapsPage;
    private javax.swing.JLabel lblColour;
    private javax.swing.JLabel lblEnterUpdate;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblstock;
    private javax.swing.JPanel pnlHeading;
    private javax.swing.ButtonGroup rdBgpFilterOptions;
    private javax.swing.JScrollPane scrDisplayCaps;
    private javax.swing.JTable tblDisplayCaps;
    private javax.swing.JTextField txtColour;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
