
import java.sql.SQLException;

import javax.swing.table.DefaultTableModel;
import javax.swing.*;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author 21nic
 */
public class CapsInfo extends javax.swing.JFrame {

    /**
     * Creates new form RacketsInfo
     */
    public TennisAlliance dbObjTennis;
    
    public String email;
    private String password; 
    

    public CapsInfo(String email, String password) {
        this.email = email;
        this.password = password;
        initComponents();
        dbObjTennis = new TennisAlliance(email);
        
        dbObjTennis.showCapsAlphabetical(tblDisplayCaps);
 this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdBgpFilterOptions = new javax.swing.ButtonGroup();
        scrDisplayCaps = new javax.swing.JScrollPane();
        tblDisplayCaps = new javax.swing.JTable();
        btnPriceAsc = new javax.swing.JRadioButton();
        btnPriceDesc = new javax.swing.JRadioButton();
        btnAddToCart = new javax.swing.JButton();
        pnlHeading = new javax.swing.JPanel();
        lblFilters = new javax.swing.JLabel();
        lblCapsPage = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        btnWhite = new javax.swing.JRadioButton();
        btnBlack = new javax.swing.JRadioButton();
        btnBlue = new javax.swing.JRadioButton();
        txtSearch = new javax.swing.JTextField();
        lblSearch = new javax.swing.JLabel();
        btnWomen = new javax.swing.JRadioButton();
        btnMens = new javax.swing.JRadioButton();
        btnCheckout = new javax.swing.JButton();
        btnFaqPage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblDisplayCaps.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblDisplayCaps.setForeground(new java.awt.Color(239, 128, 47));
        tblDisplayCaps.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cap Name", "Cap Colour", "Cap Price", "Available Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDisplayCaps.getTableHeader().setReorderingAllowed(false);
        scrDisplayCaps.setViewportView(tblDisplayCaps);
        if (tblDisplayCaps.getColumnModel().getColumnCount() > 0) {
            tblDisplayCaps.getColumnModel().getColumn(0).setResizable(false);
            tblDisplayCaps.getColumnModel().getColumn(0).setPreferredWidth(180);
            tblDisplayCaps.getColumnModel().getColumn(1).setResizable(false);
            tblDisplayCaps.getColumnModel().getColumn(2).setResizable(false);
            tblDisplayCaps.getColumnModel().getColumn(3).setResizable(false);
        }

        rdBgpFilterOptions.add(btnPriceAsc);
        btnPriceAsc.setText("Price Ascending");
        btnPriceAsc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPriceAscMouseClicked(evt);
            }
        });

        rdBgpFilterOptions.add(btnPriceDesc);
        btnPriceDesc.setText("Price Descending");
        btnPriceDesc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPriceDescMouseClicked(evt);
            }
        });

        btnAddToCart.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddToCart.setText("Add selected item to cart");
        btnAddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToCartActionPerformed(evt);
            }
        });

        pnlHeading.setBackground(new java.awt.Color(0, 102, 153));

        lblFilters.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblFilters.setForeground(new java.awt.Color(239, 128, 47));
        lblFilters.setText("Filters:");

        lblCapsPage.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblCapsPage.setForeground(new java.awt.Color(239, 128, 47));
        lblCapsPage.setText("Caps Page");

        lblMinimize.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        lblMinimize.setForeground(new java.awt.Color(255, 255, 255));
        lblMinimize.setText("-");
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
        });

        lblExit.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblExit.setForeground(new java.awt.Color(255, 255, 255));
        lblExit.setText("x");
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlHeadingLayout = new javax.swing.GroupLayout(pnlHeading);
        pnlHeading.setLayout(pnlHeadingLayout);
        pnlHeadingLayout.setHorizontalGroup(
            pnlHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeadingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFilters)
                .addGap(639, 639, 639)
                .addComponent(lblCapsPage, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 748, Short.MAX_VALUE)
                .addComponent(lblMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlHeadingLayout.setVerticalGroup(
            pnlHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeadingLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFilters)
                .addContainerGap())
            .addGroup(pnlHeadingLayout.createSequentialGroup()
                .addGroup(pnlHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlHeadingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCapsPage, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        rdBgpFilterOptions.add(btnWhite);
        btnWhite.setForeground(new java.awt.Color(255, 255, 255));
        btnWhite.setText("Colour: White");
        btnWhite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnWhiteMouseClicked(evt);
            }
        });

        rdBgpFilterOptions.add(btnBlack);
        btnBlack.setText("Colour: Black");
        btnBlack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBlackMouseClicked(evt);
            }
        });

        rdBgpFilterOptions.add(btnBlue);
        btnBlue.setForeground(new java.awt.Color(51, 51, 255));
        btnBlue.setText("Colour: Blue");
        btnBlue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBlueMouseClicked(evt);
            }
        });

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
        });

        lblSearch.setText("Search for Caps by Cap Name");

        rdBgpFilterOptions.add(btnWomen);
        btnWomen.setText("Women's Caps");
        btnWomen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnWomenMouseClicked(evt);
            }
        });

        rdBgpFilterOptions.add(btnMens);
        btnMens.setText("Men's Caps");
        btnMens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMensMouseClicked(evt);
            }
        });

        btnCheckout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCheckout.setText("Checkout");
        btnCheckout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCheckoutMouseClicked(evt);
            }
        });

        btnFaqPage.setText("FAQ");
        btnFaqPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFaqPageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnPriceAsc))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnPriceDesc))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBlack))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBlue))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnWomen))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSearch))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnMens))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnWhite)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrDisplayCaps)
                .addContainerGap())
            .addComponent(pnlHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(405, 776, Short.MAX_VALUE)
                .addComponent(btnAddToCart)
                .addGap(267, 267, 267)
                .addComponent(btnCheckout)
                .addGap(403, 403, 403))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFaqPage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHeading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnPriceAsc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPriceDesc)
                        .addGap(18, 18, 18)
                        .addComponent(btnWhite)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBlack)
                        .addGap(3, 3, 3)
                        .addComponent(btnBlue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnWomen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMens)
                        .addGap(14, 14, 14)
                        .addComponent(lblSearch)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrDisplayCaps, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
                        .addGap(47, 47, 47)))
                .addComponent(btnFaqPage)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddToCart)
                    .addComponent(btnCheckout))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPriceAscMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPriceAscMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblDisplayCaps.getModel();
        model.setRowCount(0);

        dbObjTennis.showCapsPriceAsc(tblDisplayCaps);
    }//GEN-LAST:event_btnPriceAscMouseClicked

    private void btnPriceDescMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPriceDescMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblDisplayCaps.getModel();
        model.setRowCount(0);

        dbObjTennis.showCapsPriceDesc(tblDisplayCaps);
    }//GEN-LAST:event_btnPriceDescMouseClicked

    private void btnAddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToCartActionPerformed
        TennisAlliance dbObjTennis = new TennisAlliance(email);
        DefaultTableModel model = (DefaultTableModel) tblDisplayCaps.getModel();
        int columnBag = 0;
        int columnPrice = 2;
        int row = tblDisplayCaps.getSelectedRow();
        String tempOrder = tblDisplayCaps.getModel().getValueAt(row, columnBag).toString();

        String tempOrderPrice = tblDisplayCaps.getModel().getValueAt(row, columnPrice).toString();
        String tempEmail = email;

        try {
            dbObjTennis.addOrder(tempEmail, tempOrder, tempOrderPrice);
            

            // this adds the results of the get texts to the record using .addRecord;
        } catch (SQLException ex) {
            
        }

    }//GEN-LAST:event_btnAddToCartActionPerformed

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        this.setState(JFrame.ICONIFIED);//minimizes the screen
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked

        this.dispose();
    }//GEN-LAST:event_lblExitMouseClicked

    private void btnWhiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWhiteMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblDisplayCaps.getModel();
        model.setRowCount(0);

        dbObjTennis.showCapsWhite(tblDisplayCaps);
    }//GEN-LAST:event_btnWhiteMouseClicked

    private void btnBlackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBlackMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblDisplayCaps.getModel();
        model.setRowCount(0);

        dbObjTennis.showCapsBlack(tblDisplayCaps);
    }//GEN-LAST:event_btnBlackMouseClicked

    private void btnBlueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBlueMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblDisplayCaps.getModel();
        model.setRowCount(0);

        dbObjTennis.showCapsBlue(tblDisplayCaps);         // TODO add your handling code here:
    }//GEN-LAST:event_btnBlueMouseClicked

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
       String search = txtSearch.getText();
        //making the variable equal to the text/search that was entered by the user
      //where result is like the help type entered by user

        DefaultTableModel model = (DefaultTableModel) tblDisplayCaps.getModel();
        model.setRowCount(0);

        dbObjTennis.showCapsSearch(tblDisplayCaps, search);//displaying search inside the table that was created to display the reuslts of the search
    }//GEN-LAST:event_txtSearchKeyPressed

    private void btnWomenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWomenMouseClicked
     DefaultTableModel model = (DefaultTableModel) tblDisplayCaps.getModel();
        model.setRowCount(0);

        dbObjTennis.showCapsWomen(tblDisplayCaps); 
    }//GEN-LAST:event_btnWomenMouseClicked

    private void btnMensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMensMouseClicked
         DefaultTableModel model = (DefaultTableModel) tblDisplayCaps.getModel();
        model.setRowCount(0);

        dbObjTennis.showCapsMen(tblDisplayCaps);
    }//GEN-LAST:event_btnMensMouseClicked

    private void btnCheckoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckoutMouseClicked

        new CheckOutPage(email, password).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnCheckoutMouseClicked

    private void btnFaqPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFaqPageActionPerformed
        new FAQ().setVisible(true);
    }//GEN-LAST:event_btnFaqPageActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToCart;
    private javax.swing.JRadioButton btnBlack;
    private javax.swing.JRadioButton btnBlue;
    private javax.swing.JButton btnCheckout;
    private javax.swing.JButton btnFaqPage;
    private javax.swing.JRadioButton btnMens;
    private javax.swing.JRadioButton btnPriceAsc;
    private javax.swing.JRadioButton btnPriceDesc;
    private javax.swing.JRadioButton btnWhite;
    private javax.swing.JRadioButton btnWomen;
    private javax.swing.JLabel lblCapsPage;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblFilters;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JPanel pnlHeading;
    private javax.swing.ButtonGroup rdBgpFilterOptions;
    private javax.swing.JScrollPane scrDisplayCaps;
    private javax.swing.JTable tblDisplayCaps;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
