

import java.awt.Dimension;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 21nic
 */
public class CollectionDetails extends javax.swing.JFrame {

    /**
     * Creates new form CollectionDetails
     */
    public CollectionDetails() {
        initComponents();
      this.setMinimumSize(new Dimension(1149, 750));
      this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeading = new javax.swing.JPanel();
        lblHeading = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        scrWhatAreCollectionPoints = new javax.swing.JScrollPane();
        txaWhatAreCollection = new javax.swing.JTextArea();
        lblWhatAreCollection = new javax.swing.JLabel();
        lblWhenCollection = new javax.swing.JLabel();
        scrWhenCollection = new javax.swing.JScrollPane();
        txaWhenCollection = new javax.swing.JTextArea();
        scrAboutCollection = new javax.swing.JScrollPane();
        txaAboutCollection = new javax.swing.JTextArea();
        lblAboutCollection = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        pnlHeading.setBackground(new java.awt.Color(0, 102, 153));

        lblHeading.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblHeading.setForeground(new java.awt.Color(239, 128, 47));
        lblHeading.setText("Points Of Collection");

        lblMinimize.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        lblMinimize.setForeground(new java.awt.Color(255, 255, 255));
        lblMinimize.setText("-");
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
        });

        lblExit.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblExit.setForeground(new java.awt.Color(255, 255, 255));
        lblExit.setText("x");
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlHeadingLayout = new javax.swing.GroupLayout(pnlHeading);
        pnlHeading.setLayout(pnlHeadingLayout);
        pnlHeadingLayout.setHorizontalGroup(
            pnlHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeadingLayout.createSequentialGroup()
                .addContainerGap(1052, Short.MAX_VALUE)
                .addComponent(lblMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(pnlHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeadingLayout.createSequentialGroup()
                    .addContainerGap(421, Short.MAX_VALUE)
                    .addComponent(lblHeading)
                    .addContainerGap(421, Short.MAX_VALUE)))
        );
        pnlHeadingLayout.setVerticalGroup(
            pnlHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeadingLayout.createSequentialGroup()
                .addGroup(pnlHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 92, Short.MAX_VALUE))
            .addGroup(pnlHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeadingLayout.createSequentialGroup()
                    .addContainerGap(55, Short.MAX_VALUE)
                    .addComponent(lblHeading)
                    .addContainerGap(51, Short.MAX_VALUE)))
        );

        getContentPane().add(pnlHeading);
        pnlHeading.setBounds(0, 0, 1150, 150);

        txaWhatAreCollection.setEditable(false);
        txaWhatAreCollection.setBackground(new java.awt.Color(0, 102, 153));
        txaWhatAreCollection.setColumns(20);
        txaWhatAreCollection.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        txaWhatAreCollection.setForeground(new java.awt.Color(255, 255, 255));
        txaWhatAreCollection.setLineWrap(true);
        txaWhatAreCollection.setRows(5);
        txaWhatAreCollection.setText("We have numerous collection points \nthroughout South Africa. It provides an \neasy way for customers to pick up their \norder without having to spend time \nwaiting for our delivery team.");
        scrWhatAreCollectionPoints.setViewportView(txaWhatAreCollection);

        getContentPane().add(scrWhatAreCollectionPoints);
        scrWhatAreCollectionPoints.setBounds(380, 250, 340, 270);

        lblWhatAreCollection.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblWhatAreCollection.setForeground(new java.awt.Color(239, 128, 47));
        lblWhatAreCollection.setText("What are Collection Points?");
        getContentPane().add(lblWhatAreCollection);
        lblWhatAreCollection.setBounds(400, 210, 289, 29);

        lblWhenCollection.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        lblWhenCollection.setForeground(new java.awt.Color(239, 128, 47));
        lblWhenCollection.setText("When will my order be ready for collection?");
        getContentPane().add(lblWhenCollection);
        lblWhenCollection.setBounds(740, 410, 370, 25);

        txaWhenCollection.setEditable(false);
        txaWhenCollection.setBackground(new java.awt.Color(0, 102, 153));
        txaWhenCollection.setColumns(20);
        txaWhenCollection.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        txaWhenCollection.setForeground(new java.awt.Color(255, 255, 255));
        txaWhenCollection.setLineWrap(true);
        txaWhenCollection.setRows(5);
        txaWhenCollection.setText("Products will be available for collection\nno more than 2 hours after ordering   \n(subject to stock availability.) You will\nreceive an email with detailed \ninstructions when your order is ready for\ncollection. If we are out of stock, please \nallow 1-3 days before collection.");
        scrWhenCollection.setViewportView(txaWhenCollection);

        getContentPane().add(scrWhenCollection);
        scrWhenCollection.setBounds(770, 440, 360, 230);

        txaAboutCollection.setEditable(false);
        txaAboutCollection.setBackground(new java.awt.Color(0, 102, 153));
        txaAboutCollection.setColumns(20);
        txaAboutCollection.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        txaAboutCollection.setForeground(new java.awt.Color(255, 255, 255));
        txaAboutCollection.setLineWrap(true);
        txaAboutCollection.setRows(5);
        txaAboutCollection.setText("Tennis Alliance Collection Points \nprovide you with an alternative \ndelivery location where you can \ncollect your Takealot order. \nCollectionPoints are often the fastest\nway and safest way for you to recieve \nyour equipment.");
        scrAboutCollection.setViewportView(txaAboutCollection);

        getContentPane().add(scrAboutCollection);
        scrAboutCollection.setBounds(10, 440, 330, 230);

        lblAboutCollection.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblAboutCollection.setForeground(new java.awt.Color(239, 128, 47));
        lblAboutCollection.setText("About our Collection Points");
        getContentPane().add(lblAboutCollection);
        lblAboutCollection.setBounds(10, 410, 240, 25);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesForPAT/kyrgios.jpg"))); // NOI18N
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 150, 1150, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        this.setState(JFrame.ICONIFIED);//minimizes the screen
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
       

        dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_lblExitMouseClicked

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAboutCollection;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblWhatAreCollection;
    private javax.swing.JLabel lblWhenCollection;
    private javax.swing.JPanel pnlHeading;
    private javax.swing.JScrollPane scrAboutCollection;
    private javax.swing.JScrollPane scrWhatAreCollectionPoints;
    private javax.swing.JScrollPane scrWhenCollection;
    private javax.swing.JTextArea txaAboutCollection;
    private javax.swing.JTextArea txaWhatAreCollection;
    private javax.swing.JTextArea txaWhenCollection;
    // End of variables declaration//GEN-END:variables
}
