
import java.awt.Dimension;
import javax.swing.JFrame;






/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 21nic
 */
public class FAQ extends javax.swing.JFrame {

    /**
     * Creates new form FAQ
     */
    public FAQ() {
        initComponents();
        
       this.setMinimumSize(new Dimension(957, 740));
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeading = new javax.swing.JPanel();
        lblHeadingFAQ = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        lblAbtAlliance = new javax.swing.JLabel();
        lblCollection = new javax.swing.JLabel();
        lblPayments = new javax.swing.JLabel();
        lblAdditionalContactInfo = new javax.swing.JLabel();
        lblWhoAreWe = new javax.swing.JLabel();
        lblHowToPay = new javax.swing.JLabel();
        lblCOD = new javax.swing.JLabel();
        lblConfirmationEmail = new javax.swing.JLabel();
        lblCollectionPoints = new javax.swing.JLabel();
        lblCollectionTime = new javax.swing.JLabel();
        lblCreateAccount = new javax.swing.JLabel();
        lblTechSupport = new javax.swing.JLabel();
        lblContact = new javax.swing.JLabel();
        lblBackgroundFAQ = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().setLayout(null);

        pnlHeading.setBackground(new java.awt.Color(0, 102, 153));

        lblHeadingFAQ.setBackground(new java.awt.Color(255, 51, 51));
        lblHeadingFAQ.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblHeadingFAQ.setForeground(new java.awt.Color(239, 128, 47));
        lblHeadingFAQ.setText("Frequently Asked Questions");

        lblMinimize.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        lblMinimize.setForeground(new java.awt.Color(255, 255, 255));
        lblMinimize.setText("-");
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
        });

        lblExit.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblExit.setForeground(new java.awt.Color(255, 255, 255));
        lblExit.setText("x");
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlHeadingLayout = new javax.swing.GroupLayout(pnlHeading);
        pnlHeading.setLayout(pnlHeadingLayout);
        pnlHeadingLayout.setHorizontalGroup(
            pnlHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeadingLayout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(lblHeadingFAQ)
                .addContainerGap(303, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeadingLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        pnlHeadingLayout.setVerticalGroup(
            pnlHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeadingLayout.createSequentialGroup()
                .addGroup(pnlHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHeadingLayout.createSequentialGroup()
                        .addComponent(lblExit)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeadingLayout.createSequentialGroup()
                        .addComponent(lblMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(lblHeadingFAQ)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        getContentPane().add(pnlHeading);
        pnlHeading.setBounds(0, 0, 960, 170);

        lblAbtAlliance.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAbtAlliance.setText("About Tennis Alliance");
        lblAbtAlliance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(lblAbtAlliance);
        lblAbtAlliance.setBounds(48, 274, 170, 22);

        lblCollection.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCollection.setText("Collection");
        getContentPane().add(lblCollection);
        lblCollection.setBounds(640, 270, 76, 22);

        lblPayments.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPayments.setText("Payments");
        getContentPane().add(lblPayments);
        lblPayments.setBounds(48, 412, 76, 22);

        lblAdditionalContactInfo.setText("• Additional Contact Information");
        lblAdditionalContactInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAdditionalContactInfoMouseClicked(evt);
            }
        });
        getContentPane().add(lblAdditionalContactInfo);
        lblAdditionalContactInfo.setBounds(48, 332, 230, 14);

        lblWhoAreWe.setText("• Who are we?");
        lblWhoAreWe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblWhoAreWeMouseClicked(evt);
            }
        });
        getContentPane().add(lblWhoAreWe);
        lblWhoAreWe.setBounds(48, 307, 230, 14);

        lblHowToPay.setText("• How can I pay for my order?");
        lblHowToPay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHowToPayMouseClicked(evt);
            }
        });
        getContentPane().add(lblHowToPay);
        lblHowToPay.setBounds(48, 440, 260, 14);

        lblCOD.setText("• Why can I not pay with cash on delivery(COD)?");
        lblCOD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCODMouseClicked(evt);
            }
        });
        getContentPane().add(lblCOD);
        lblCOD.setBounds(48, 465, 360, 14);

        lblConfirmationEmail.setText("• Why haven't I received my payment confirmation email?");
        lblConfirmationEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConfirmationEmailMouseClicked(evt);
            }
        });
        getContentPane().add(lblConfirmationEmail);
        lblConfirmationEmail.setBounds(48, 490, 400, 14);

        lblCollectionPoints.setText("• About our collection points");
        lblCollectionPoints.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCollectionPointsMouseClicked(evt);
            }
        });
        getContentPane().add(lblCollectionPoints);
        lblCollectionPoints.setBounds(640, 300, 300, 14);

        lblCollectionTime.setText("• When will my order be ready for collection?");
        lblCollectionTime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCollectionTimeMouseClicked(evt);
            }
        });
        getContentPane().add(lblCollectionTime);
        lblCollectionTime.setBounds(640, 320, 310, 20);

        lblCreateAccount.setText("• How do I create an account on Tennis Alliance?");
        lblCreateAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCreateAccountMouseClicked(evt);
            }
        });
        getContentPane().add(lblCreateAccount);
        lblCreateAccount.setBounds(640, 460, 310, 14);

        lblTechSupport.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTechSupport.setText("Technical Support");
        getContentPane().add(lblTechSupport);
        lblTechSupport.setBounds(640, 410, 141, 22);

        lblContact.setText("• How can I contact a tech support member?");
        lblContact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblContactMouseClicked(evt);
            }
        });
        getContentPane().add(lblContact);
        lblContact.setBounds(640, 440, 300, 14);

        lblBackgroundFAQ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesForPAT/Nadal1-1100x600.jpg"))); // NOI18N
        getContentPane().add(lblBackgroundFAQ);
        lblBackgroundFAQ.setBounds(0, 161, 960, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblWhoAreWeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblWhoAreWeMouseClicked
         new AboutUs().setVisible(true);
           
            
       
    }//GEN-LAST:event_lblWhoAreWeMouseClicked

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
 this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked

           
            
        dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblAdditionalContactInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdditionalContactInfoMouseClicked
        new AdditionalContact().setVisible(true);
    }//GEN-LAST:event_lblAdditionalContactInfoMouseClicked

    private void lblHowToPayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHowToPayMouseClicked
       new PaymentOptions().setVisible(true);
    }//GEN-LAST:event_lblHowToPayMouseClicked

    private void lblCollectionPointsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCollectionPointsMouseClicked
       new CollectionDetails().setVisible(true);
    }//GEN-LAST:event_lblCollectionPointsMouseClicked

    private void lblCollectionTimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCollectionTimeMouseClicked
       new CollectionDetails().setVisible(true);
    }//GEN-LAST:event_lblCollectionTimeMouseClicked

    private void lblContactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContactMouseClicked
        new AdditionalContact().setVisible(true);
    }//GEN-LAST:event_lblContactMouseClicked

    private void lblCreateAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreateAccountMouseClicked
         new TechCreateAccHelp().setVisible(true);
    }//GEN-LAST:event_lblCreateAccountMouseClicked

    private void lblCODMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCODMouseClicked
new COD().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_lblCODMouseClicked

    private void lblConfirmationEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfirmationEmailMouseClicked
new ConfirmationEmail().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_lblConfirmationEmailMouseClicked

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAbtAlliance;
    private javax.swing.JLabel lblAdditionalContactInfo;
    private javax.swing.JLabel lblBackgroundFAQ;
    private javax.swing.JLabel lblCOD;
    private javax.swing.JLabel lblCollection;
    private javax.swing.JLabel lblCollectionPoints;
    private javax.swing.JLabel lblCollectionTime;
    private javax.swing.JLabel lblConfirmationEmail;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblCreateAccount;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblHeadingFAQ;
    private javax.swing.JLabel lblHowToPay;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblPayments;
    private javax.swing.JLabel lblTechSupport;
    private javax.swing.JLabel lblWhoAreWe;
    private javax.swing.JPanel pnlHeading;
    // End of variables declaration//GEN-END:variables
}
