
import java.awt.Dimension;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author 21nic
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form FAQ
     */
    private String email;
    private String password; 
    

    public MainPage(String email, String password) {
        
        this.email = email;
this.password = password; 
        initComponents();

        this.setMinimumSize(new Dimension(1279, 852));
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblShopping = new javax.swing.JLabel();
        lblViewOur = new javax.swing.JLabel();
        lblEntireCollection = new javax.swing.JLabel();
        lblBasket = new javax.swing.JLabel();
        lblMoreInfo = new javax.swing.JLabel();
        lblCollection = new javax.swing.JLabel();
        lblRackets = new javax.swing.JLabel();
        lblPayments = new javax.swing.JLabel();
        lblFAQ = new javax.swing.JLabel();
        lblOtherHelp = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        lblHeading = new javax.swing.JLabel();
        lblBalls = new javax.swing.JLabel();
        lblBags = new javax.swing.JLabel();
        lblCaps = new javax.swing.JLabel();
        lblStrings = new javax.swing.JLabel();
        lblHelp = new javax.swing.JLabel();
        lblTechSupport = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().setLayout(null);

        lblShopping.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblShopping.setForeground(new java.awt.Color(255, 255, 255));
        lblShopping.setText("Shop Our Equipment");
        lblShopping.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(lblShopping);
        lblShopping.setBounds(48, 223, 510, 80);

        lblViewOur.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblViewOur.setForeground(new java.awt.Color(255, 255, 255));
        lblViewOur.setText("View Our");
        getContentPane().add(lblViewOur);
        lblViewOur.setBounds(40, 530, 300, 60);

        lblEntireCollection.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblEntireCollection.setForeground(new java.awt.Color(255, 255, 255));
        lblEntireCollection.setText("• View Our Entire Collection");
        lblEntireCollection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEntireCollectionMouseClicked(evt);
            }
        });
        getContentPane().add(lblEntireCollection);
        lblEntireCollection.setBounds(50, 300, 420, 40);

        lblBasket.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblBasket.setForeground(new java.awt.Color(255, 255, 255));
        lblBasket.setText("• View your basket");
        lblBasket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBasketMouseClicked(evt);
            }
        });
        getContentPane().add(lblBasket);
        lblBasket.setBounds(50, 340, 530, 70);

        lblMoreInfo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblMoreInfo.setForeground(new java.awt.Color(255, 255, 255));
        lblMoreInfo.setText("• More info about Tennis Alliance");
        lblMoreInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMoreInfoMouseClicked(evt);
            }
        });
        getContentPane().add(lblMoreInfo);
        lblMoreInfo.setBounds(830, 750, 420, 70);

        lblCollection.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblCollection.setForeground(new java.awt.Color(255, 255, 255));
        lblCollection.setText("• Information about collection");
        lblCollection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCollectionMouseClicked(evt);
            }
        });
        getContentPane().add(lblCollection);
        lblCollection.setBounds(830, 600, 400, 60);

        lblRackets.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblRackets.setForeground(new java.awt.Color(255, 255, 255));
        lblRackets.setText("• Rackets");
        lblRackets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRacketsMouseClicked(evt);
            }
        });
        getContentPane().add(lblRackets);
        lblRackets.setBounds(50, 760, 130, 60);

        lblPayments.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblPayments.setForeground(new java.awt.Color(255, 255, 255));
        lblPayments.setText("• Payment options");
        lblPayments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPaymentsMouseClicked(evt);
            }
        });
        getContentPane().add(lblPayments);
        lblPayments.setBounds(830, 650, 370, 60);

        lblFAQ.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblFAQ.setForeground(new java.awt.Color(255, 255, 255));
        lblFAQ.setText("• Visit our FAQ page");
        lblFAQ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFAQMouseClicked(evt);
            }
        });
        getContentPane().add(lblFAQ);
        lblFAQ.setBounds(840, 290, 380, 50);

        lblOtherHelp.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblOtherHelp.setForeground(new java.awt.Color(255, 255, 255));
        lblOtherHelp.setText("Additional Help");
        getContentPane().add(lblOtherHelp);
        lblOtherHelp.setBounds(830, 530, 380, 70);

        lblMinimize.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        lblMinimize.setForeground(new java.awt.Color(255, 255, 255));
        lblMinimize.setText("-");
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
        });
        getContentPane().add(lblMinimize);
        lblMinimize.setBounds(1200, 20, 22, 73);

        lblExit.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblExit.setForeground(new java.awt.Color(255, 255, 255));
        lblExit.setText("x");
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });
        getContentPane().add(lblExit);
        lblExit.setBounds(1230, 30, 24, 58);

        lblHeading.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        lblHeading.setForeground(new java.awt.Color(0, 102, 153));
        lblHeading.setText("Tennis Alliance");
        getContentPane().add(lblHeading);
        lblHeading.setBounds(180, 60, 810, 121);

        lblBalls.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblBalls.setForeground(new java.awt.Color(255, 255, 255));
        lblBalls.setText("• Balls");
        lblBalls.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBallsMouseClicked(evt);
            }
        });
        getContentPane().add(lblBalls);
        lblBalls.setBounds(50, 720, 110, 50);

        lblBags.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblBags.setForeground(new java.awt.Color(255, 255, 255));
        lblBags.setText("• Bags");
        lblBags.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBagsMouseClicked(evt);
            }
        });
        getContentPane().add(lblBags);
        lblBags.setBounds(50, 630, 140, 60);

        lblCaps.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblCaps.setForeground(new java.awt.Color(255, 255, 255));
        lblCaps.setText("• Caps");
        lblCaps.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCapsMouseClicked(evt);
            }
        });
        getContentPane().add(lblCaps);
        lblCaps.setBounds(50, 680, 110, 50);

        lblStrings.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblStrings.setForeground(new java.awt.Color(255, 255, 255));
        lblStrings.setText("• Strings");
        lblStrings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblStringsMouseClicked(evt);
            }
        });
        getContentPane().add(lblStrings);
        lblStrings.setBounds(50, 590, 140, 50);

        lblHelp.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblHelp.setForeground(new java.awt.Color(255, 255, 255));
        lblHelp.setText("Need Help");
        getContentPane().add(lblHelp);
        lblHelp.setBounds(830, 230, 320, 70);

        lblTechSupport.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTechSupport.setForeground(new java.awt.Color(255, 255, 255));
        lblTechSupport.setText("• Technical support");
        lblTechSupport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTechSupportMouseClicked(evt);
            }
        });
        getContentPane().add(lblTechSupport);
        lblTechSupport.setBounds(830, 700, 420, 70);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesForPAT/racket.jpg"))); // NOI18N
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, -20, 1280, 890);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblEntireCollectionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEntireCollectionMouseClicked
        new EntireCollectionPage(email, password).setVisible(true);


    }//GEN-LAST:event_lblEntireCollectionMouseClicked

    private void lblRacketsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRacketsMouseClicked
        new RacketsInfo(email, password).setVisible(true);
    }//GEN-LAST:event_lblRacketsMouseClicked

    private void lblCollectionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCollectionMouseClicked
new CollectionDetails().setVisible(true);
    }//GEN-LAST:event_lblCollectionMouseClicked

    private void lblMoreInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMoreInfoMouseClicked
        new AboutUs().setVisible(true);
    }//GEN-LAST:event_lblMoreInfoMouseClicked

    private void lblPaymentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPaymentsMouseClicked
        new PaymentOptions().setVisible(true);
    }//GEN-LAST:event_lblPaymentsMouseClicked

    private void lblFAQMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFAQMouseClicked
        new FAQ().setVisible(true);
    }//GEN-LAST:event_lblFAQMouseClicked

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked

        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblBallsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBallsMouseClicked
        new BallsInfo(email, password).setVisible(true);
    }//GEN-LAST:event_lblBallsMouseClicked

    private void lblBagsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBagsMouseClicked
        new BagsInfo(email, password).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_lblBagsMouseClicked

    private void lblCapsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCapsMouseClicked
        new CapsInfo(email, password).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_lblCapsMouseClicked

    private void lblStringsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStringsMouseClicked
        new StringsInfo(email, password).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_lblStringsMouseClicked

    private void lblTechSupportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTechSupportMouseClicked
new AdditionalContact().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_lblTechSupportMouseClicked

    private void lblBasketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBasketMouseClicked
new CheckOutPage(email, password).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_lblBasketMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBags;
    private javax.swing.JLabel lblBalls;
    private javax.swing.JLabel lblBasket;
    private javax.swing.JLabel lblCaps;
    private javax.swing.JLabel lblCollection;
    private javax.swing.JLabel lblEntireCollection;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblFAQ;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblHelp;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblMoreInfo;
    private javax.swing.JLabel lblOtherHelp;
    private javax.swing.JLabel lblPayments;
    private javax.swing.JLabel lblRackets;
    private javax.swing.JLabel lblShopping;
    private javax.swing.JLabel lblStrings;
    private javax.swing.JLabel lblTechSupport;
    private javax.swing.JLabel lblViewOur;
    // End of variables declaration//GEN-END:variables
}
