/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 21nic
 */
public class OrderSuccessful extends javax.swing.JFrame {

    /**
     * Creates new form WelcomeMessage
     */
    public TennisAlliance dbObjTennis;
    private String email;
    private String password; 
       
        
    public OrderSuccessful(String email, String password) {
        this.password = password; 
        this.email = email;
        initComponents();
         
         dbObjTennis = new TennisAlliance(email);
        lblTSANum.setText(dbObjTennis.getTSA(email, password));
        lblName.setText(dbObjTennis.getName(email, password));
        lblTotalPriceResults.setText("R "+dbObjTennis.calcTotalPrice(email));
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSuccessForm = new javax.swing.JPanel();
        lblSuccess = new javax.swing.JLabel();
        lblTSANum = new javax.swing.JLabel();
        btnProceed = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();
        scrPaymentOptions = new javax.swing.JScrollPane();
        txaPayment = new javax.swing.JTextArea();
        lblTotalPrice = new javax.swing.JLabel();
        lblTotalPriceResults = new javax.swing.JLabel();
        lblInstructions = new javax.swing.JLabel();
        btnFaqPage = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        lblYourTsaNum = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlSuccessForm.setBackground(new java.awt.Color(239, 128, 47));
        pnlSuccessForm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153), 15));

        lblSuccess.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblSuccess.setForeground(new java.awt.Color(0, 102, 153));
        lblSuccess.setText("Your Order is being processed,");

        lblTSANum.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTSANum.setForeground(new java.awt.Color(0, 102, 153));

        btnProceed.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnProceed.setText("Proceed");
        btnProceed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProceedMouseClicked(evt);
            }
        });

        btnHelp.setText("Payment Help ");
        btnHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHelpMouseClicked(evt);
            }
        });

        txaPayment.setEditable(false);
        txaPayment.setColumns(20);
        txaPayment.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        txaPayment.setForeground(new java.awt.Color(0, 102, 153));
        txaPayment.setRows(5);
        txaPayment.setText("To view our payment options page, click the button located\nin the bottom right. \n\nDelivery will only commence once payment confirmation has\nbeen recieved by Tennis Alliance Admin. \n\nThe most popular forms of payment include: EFT, Paypal\nor PayFast. \n\nAccount: tennis@alliance.co.za\n\nUse your above mentioned TSANumber to track your order!\n");
        scrPaymentOptions.setViewportView(txaPayment);

        lblTotalPrice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTotalPrice.setForeground(new java.awt.Color(0, 102, 153));
        lblTotalPrice.setText("Your order total is:");

        lblTotalPriceResults.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTotalPriceResults.setForeground(new java.awt.Color(0, 102, 153));

        lblInstructions.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblInstructions.setText("(Please make the payment of the above mentioned amount in order for your order to be delivered)");

        btnFaqPage.setText("FAQ ");
        btnFaqPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFaqPageActionPerformed(evt);
            }
        });

        lblName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 102, 153));

        lblYourTsaNum.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblYourTsaNum.setForeground(new java.awt.Color(0, 102, 153));
        lblYourTsaNum.setText("Your TSA Num:");

        javax.swing.GroupLayout pnlSuccessFormLayout = new javax.swing.GroupLayout(pnlSuccessForm);
        pnlSuccessForm.setLayout(pnlSuccessFormLayout);
        pnlSuccessFormLayout.setHorizontalGroup(
            pnlSuccessFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuccessFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSuccessFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSuccessFormLayout.createSequentialGroup()
                        .addGroup(pnlSuccessFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFaqPage)
                            .addComponent(btnHelp))
                        .addGap(18, 18, 18)
                        .addGroup(pnlSuccessFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlSuccessFormLayout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addGroup(pnlSuccessFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblInstructions)
                                    .addGroup(pnlSuccessFormLayout.createSequentialGroup()
                                        .addComponent(lblTotalPrice)
                                        .addGap(10, 10, 10)
                                        .addComponent(lblTotalPriceResults, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 296, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSuccessFormLayout.createSequentialGroup()
                                .addComponent(btnProceed, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSuccessFormLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(scrPaymentOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblYourTsaNum)
                        .addGap(32, 32, 32)
                        .addComponent(lblTSANum, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(pnlSuccessFormLayout.createSequentialGroup()
                        .addComponent(lblSuccess)
                        .addGap(18, 18, 18)
                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlSuccessFormLayout.setVerticalGroup(
            pnlSuccessFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuccessFormLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlSuccessFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSuccess, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlSuccessFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSuccessFormLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(scrPaymentOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(pnlSuccessFormLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(pnlSuccessFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTSANum, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblYourTsaNum, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(pnlSuccessFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSuccessFormLayout.createSequentialGroup()
                        .addGroup(pnlSuccessFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotalPrice, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTotalPriceResults, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblInstructions)
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSuccessFormLayout.createSequentialGroup()
                        .addComponent(btnFaqPage)
                        .addGap(14, 14, 14)))
                .addGroup(pnlSuccessFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnProceed)
                    .addComponent(btnHelp))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlSuccessForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSuccessForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHelpMouseClicked
        new PaymentOptions().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnHelpMouseClicked

    private void btnProceedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProceedMouseClicked

        this.dispose();
        new ThanksForShopping(email, password).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnProceedMouseClicked

    private void btnFaqPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFaqPageActionPerformed
new FAQ().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnFaqPageActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFaqPage;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnProceed;
    private javax.swing.JLabel lblInstructions;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSuccess;
    private javax.swing.JLabel lblTSANum;
    private javax.swing.JLabel lblTotalPrice;
    private javax.swing.JLabel lblTotalPriceResults;
    private javax.swing.JLabel lblYourTsaNum;
    private javax.swing.JPanel pnlSuccessForm;
    private javax.swing.JScrollPane scrPaymentOptions;
    private javax.swing.JTextArea txaPayment;
    // End of variables declaration//GEN-END:variables
}
