

import java.sql.SQLException;

import javax.swing.table.DefaultTableModel;
import javax.swing.*;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author 21nic
 */
public class RacketsInfoAdmin extends javax.swing.JFrame {

  

    /**
     * Creates new form RacketsInfo
     */
    public TennisAlliance dbObjTennis;
   
 
    public String email;

    

    public RacketsInfoAdmin(String email) {

        this.email = email;
        initComponents();
        dbObjTennis = new TennisAlliance(email);
       
        dbObjTennis.showRacketsAlphabetical(tblDisplayRackets);
         this.setLocationRelativeTo(null);

    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrDisplayRackets = new javax.swing.JScrollPane();
        tblDisplayRackets = new javax.swing.JTable();
        pnlHeading = new javax.swing.JPanel();
        lblRacketsPage = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        lblSearch = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        lblRacketName = new javax.swing.JLabel();
        lblWeight = new javax.swing.JLabel();
        txtWeight = new javax.swing.JTextField();
        txtRacketCol = new javax.swing.JTextField();
        lblRacketColour = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnNewRecord = new javax.swing.JButton();
        txtPrice = new javax.swing.JTextField();
        lblPrice = new javax.swing.JLabel();
        lblEnterUpdate = new javax.swing.JLabel();
        lblStringPrice = new javax.swing.JLabel();
        txtStringPattern = new javax.swing.JTextField();
        txtSwingWeight = new javax.swing.JTextField();
        lblSwingWeight = new javax.swing.JLabel();
        lblVibration = new javax.swing.JLabel();
        txtVibration = new javax.swing.JTextField();
        txtPower = new javax.swing.JTextField();
        lblPower = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        lblModel = new javax.swing.JLabel();
        lblLength = new javax.swing.JLabel();
        txtLength = new javax.swing.JTextField();
        lblStock = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblDisplayRackets.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblDisplayRackets.setForeground(new java.awt.Color(239, 128, 47));
        tblDisplayRackets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RacketName", "RacketWeight(g)", "RacketColour", "RacketPrice(Rands)", "StringPattern", "SwingWeight_kg*cm2", "Vibration_Hz", "Power_%", "RacketModel", "Length_cm", "AvailableStock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDisplayRackets.getTableHeader().setReorderingAllowed(false);
        scrDisplayRackets.setViewportView(tblDisplayRackets);
        if (tblDisplayRackets.getColumnModel().getColumnCount() > 0) {
            tblDisplayRackets.getColumnModel().getColumn(0).setResizable(false);
            tblDisplayRackets.getColumnModel().getColumn(0).setPreferredWidth(140);
            tblDisplayRackets.getColumnModel().getColumn(1).setResizable(false);
            tblDisplayRackets.getColumnModel().getColumn(2).setResizable(false);
            tblDisplayRackets.getColumnModel().getColumn(3).setResizable(false);
            tblDisplayRackets.getColumnModel().getColumn(4).setResizable(false);
            tblDisplayRackets.getColumnModel().getColumn(5).setResizable(false);
            tblDisplayRackets.getColumnModel().getColumn(6).setResizable(false);
            tblDisplayRackets.getColumnModel().getColumn(7).setResizable(false);
            tblDisplayRackets.getColumnModel().getColumn(8).setResizable(false);
            tblDisplayRackets.getColumnModel().getColumn(9).setResizable(false);
            tblDisplayRackets.getColumnModel().getColumn(10).setResizable(false);
        }

        pnlHeading.setBackground(new java.awt.Color(0, 102, 153));

        lblRacketsPage.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblRacketsPage.setForeground(new java.awt.Color(239, 128, 47));
        lblRacketsPage.setText("Rackets Page Admin");

        lblMinimize.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        lblMinimize.setForeground(new java.awt.Color(255, 255, 255));
        lblMinimize.setText("-");
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
        });

        lblExit.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblExit.setForeground(new java.awt.Color(255, 255, 255));
        lblExit.setText("x");
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlHeadingLayout = new javax.swing.GroupLayout(pnlHeading);
        pnlHeading.setLayout(pnlHeadingLayout);
        pnlHeadingLayout.setHorizontalGroup(
            pnlHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeadingLayout.createSequentialGroup()
                .addGap(721, 721, 721)
                .addComponent(lblRacketsPage, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 633, Short.MAX_VALUE)
                .addComponent(lblMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlHeadingLayout.setVerticalGroup(
            pnlHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeadingLayout.createSequentialGroup()
                .addGroup(pnlHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlHeadingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRacketsPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
        });

        lblSearch.setText("Search for Racket");

        btnDelete.setText("Delete Selected Record");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });

        txtName.setPreferredSize(new java.awt.Dimension(100, 25));

        lblRacketName.setText("Racket Name");

        lblWeight.setText("Racket Weight(g)");

        txtWeight.setPreferredSize(new java.awt.Dimension(100, 25));

        txtRacketCol.setPreferredSize(new java.awt.Dimension(100, 25));

        lblRacketColour.setText("Racket colour");

        btnUpdate.setText("Update");
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });

        btnNewRecord.setText("Create New Record");
        btnNewRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewRecordMouseClicked(evt);
            }
        });

        txtPrice.setPreferredSize(new java.awt.Dimension(100, 25));

        lblPrice.setText("RacketPrice(Rands)");

        lblEnterUpdate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEnterUpdate.setForeground(new java.awt.Color(51, 0, 255));
        lblEnterUpdate.setText("Enter New values to update Selected field");

        lblStringPrice.setText("String Pattern");

        txtStringPattern.setPreferredSize(new java.awt.Dimension(100, 25));

        txtSwingWeight.setPreferredSize(new java.awt.Dimension(100, 25));

        lblSwingWeight.setText("SwingWeight_kg*cm2");

        lblVibration.setText("Vibration_Hz");

        txtVibration.setPreferredSize(new java.awt.Dimension(100, 25));

        txtPower.setPreferredSize(new java.awt.Dimension(100, 25));

        lblPower.setText("Power_%");

        txtModel.setPreferredSize(new java.awt.Dimension(100, 25));

        lblModel.setText("RacketModel(YYYY/MM/DD)");

        lblLength.setText("Length_cm");

        txtLength.setPreferredSize(new java.awt.Dimension(100, 25));

        lblStock.setText("Available Stock");

        txtStock.setPreferredSize(new java.awt.Dimension(100, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSearch)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(scrDisplayRackets, javax.swing.GroupLayout.PREFERRED_SIZE, 1643, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDelete)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(494, 494, 494)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblPrice)
                                                .addGap(91, 91, 91)
                                                .addComponent(lblStringPrice)
                                                .addGap(96, 96, 96)
                                                .addComponent(lblSwingWeight))
                                            .addComponent(txtPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(70, 70, 70)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblVibration)
                                            .addComponent(txtVibration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblEnterUpdate)
                                        .addGap(40, 40, 40)))
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPower, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPower))
                                .addGap(71, 71, 71)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtModel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblModel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLength, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLength))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblStock)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnUpdate)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblRacketName)
                                                .addGap(98, 98, 98))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(56, 56, 56)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtWeight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblWeight))
                                        .addGap(75, 75, 75)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblRacketColour)
                                            .addComponent(txtRacketCol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(243, 243, 243)
                                        .addComponent(txtStringPattern, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addComponent(txtSwingWeight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(100, 100, 100)
                                        .addComponent(btnNewRecord)))
                                .addGap(3, 3, 3)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlHeading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblSearch)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(scrDisplayRackets, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblEnterUpdate)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDelete)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblSwingWeight)
                                .addComponent(lblVibration)
                                .addComponent(lblPower)
                                .addComponent(lblModel)
                                .addComponent(lblLength))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtSwingWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtVibration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblStock)
                            .addGap(18, 18, 18)
                            .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRacketName)
                            .addComponent(lblWeight)
                            .addComponent(lblRacketColour)
                            .addComponent(lblPrice)
                            .addComponent(lblStringPrice))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStringPattern, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtRacketCol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnNewRecord))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        this.setState(JFrame.ICONIFIED);//minimizes the screen
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked

        this.dispose();
    }//GEN-LAST:event_lblExitMouseClicked

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
    String search = txtSearch.getText();
        //making the variable equal to the text/search that was entered by the user
      //where result is like the help type entered by user

        DefaultTableModel model = (DefaultTableModel) tblDisplayRackets.getModel();
        model.setRowCount(0);

        dbObjTennis.showRacketsSearch(tblDisplayRackets, search);//displaying search inside the table that was created to display the reuslts of the search
    }//GEN-LAST:event_txtSearchKeyPressed

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblDisplayRackets.getModel();
        int columnRacket = 0;
        int columnColour= 2;
        int row = tblDisplayRackets.getSelectedRow();
      
        String tempOrderRacket = tblDisplayRackets.getModel().getValueAt(row, columnRacket).toString();
        String tempOrderColour = tblDisplayRackets.getModel().getValueAt(row, columnColour).toString();
        
        //updating where the ID is what they entered the ID to be
        try{//try catch here in order to try and catch the SQLExcepption error
            dbObjTennis.deleteRacket(tempOrderRacket, tempOrderColour);//this is used to update the record
            JOptionPane.showMessageDialog(null, "Item has been successfully removed!");
            model.setRowCount(0);
            DefaultTableModel modelRefreshed = (DefaultTableModel) tblDisplayRackets.getModel();
            dbObjTennis.showRacketsAlphabetical(tblDisplayRackets);
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Record was not deleted " +e);

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblDisplayRackets.getModel();
        int columnRackets = 0;
        int columnColour = 2;
        int row = tblDisplayRackets.getSelectedRow();
        
        String tempOrderRackets = tblDisplayRackets.getModel().getValueAt(row, columnRackets).toString();
        String tempOrderColour = tblDisplayRackets.getModel().getValueAt(row, columnColour).toString();

        String name = txtName.getText();
  int weight = Integer.parseInt(txtWeight.getText());
        String colour = txtRacketCol.getText();
        int price = Integer.parseInt(txtPrice.getText());
        String pattern = txtStringPattern.getText();
        int swingWeight = Integer.parseInt(txtSwingWeight.getText());
        int vibration= Integer.parseInt(txtVibration.getText());
        int power = Integer.parseInt(txtPower.getText());
        String racketModel = txtModel.getText();
        int length = Integer.parseInt(txtLength.getText());
        int stock = Integer.parseInt(txtStock.getText());
        
        
       
      
//updating where the ID is what they entered the ID to be
        try{//try catch here in order to try and catch the SQLExcepption error
            dbObjTennis.updateRacket(tempOrderRackets, tempOrderColour, name, weight, colour, price, pattern, swingWeight, vibration, power, racketModel, length, stock);//this is used to update the record
            JOptionPane.showMessageDialog(null, "Item has been successfully updated!");
            model.setRowCount(0);
            DefaultTableModel modelRefreshed = (DefaultTableModel) tblDisplayRackets.getModel();
            dbObjTennis.showRacketsAlphabetical(tblDisplayRackets);
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Cannot insert record\n " +e);

        }
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void btnNewRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewRecordMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblDisplayRackets.getModel();
       
       

        String name = txtName.getText();
  int weight = Integer.parseInt(txtWeight.getText());
        String colour = txtRacketCol.getText();
        int price = Integer.parseInt(txtPrice.getText());
        String pattern = txtStringPattern.getText();
        int swingWeight = Integer.parseInt(txtSwingWeight.getText());
        int vibration= Integer.parseInt(txtVibration.getText());
        int power = Integer.parseInt(txtPower.getText());
        String racketModel = txtModel.getText();
        int length = Integer.parseInt(txtLength.getText());
        int stock = Integer.parseInt(txtStock.getText());
        
        
        
        //updating where the ID is what they entered the ID to be
        try{//try catch here in order to try and catch the SQLExcepption error
            dbObjTennis.insertRacket(name, weight, colour, price, pattern, swingWeight, vibration, power, racketModel, length, stock);//this is used to update the record
            JOptionPane.showMessageDialog(null, "Item has been successfully updated!");
            model.setRowCount(0);
            DefaultTableModel modelRefreshed = (DefaultTableModel) tblDisplayRackets.getModel();
            dbObjTennis.showRacketsAlphabetical(tblDisplayRackets);
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Cannot insert record\n " +e);

        }
    }//GEN-LAST:event_btnNewRecordMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNewRecord;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblEnterUpdate;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblLength;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblPower;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblRacketColour;
    private javax.swing.JLabel lblRacketName;
    private javax.swing.JLabel lblRacketsPage;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblStringPrice;
    private javax.swing.JLabel lblSwingWeight;
    private javax.swing.JLabel lblVibration;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JPanel pnlHeading;
    private javax.swing.JScrollPane scrDisplayRackets;
    private javax.swing.JTable tblDisplayRackets;
    private javax.swing.JTextField txtLength;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPower;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtRacketCol;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtStringPattern;
    private javax.swing.JTextField txtSwingWeight;
    private javax.swing.JTextField txtVibration;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
