
import java.sql.SQLException;

import javax.swing.table.DefaultTableModel;
import javax.swing.*;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author 21nic
 */
public class StringsInfoAdmin extends javax.swing.JFrame {

  

    /**
     * Creates new form RacketsInfo
     */
    public TennisAlliance dbObjTennis;
   
    public String email;
 
    

    public StringsInfoAdmin(String email) {

        this.email = email;
        initComponents();
       dbObjTennis =  new TennisAlliance(email);
        
        dbObjTennis.showStringsAlphabetical(tblDisplayStrings);
         this.setLocationRelativeTo(null);

    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrDisplayRackets = new javax.swing.JScrollPane();
        tblDisplayStrings = new javax.swing.JTable();
        pnlHeading = new javax.swing.JPanel();
        lblStringsAdminPage = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        lblSearch = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtStringComp = new javax.swing.JTextField();
        txtStringCol = new javax.swing.JTextField();
        txtStringGuage = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        txtStringPrice = new javax.swing.JTextField();
        lblStringName = new javax.swing.JLabel();
        lblStringComp = new javax.swing.JLabel();
        lblStringColour = new javax.swing.JLabel();
        lblStringGuage = new javax.swing.JLabel();
        lblStringPrice = new javax.swing.JLabel();
        lblstock = new javax.swing.JLabel();
        lblEnterUpdate = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnNewRecord = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblDisplayStrings.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblDisplayStrings.setForeground(new java.awt.Color(239, 128, 47));
        tblDisplayStrings.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "String Name", "String Composition", "String Colour", "String Gauge", "String Price(Rands)", "Available Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDisplayStrings.getTableHeader().setReorderingAllowed(false);
        scrDisplayRackets.setViewportView(tblDisplayStrings);
        if (tblDisplayStrings.getColumnModel().getColumnCount() > 0) {
            tblDisplayStrings.getColumnModel().getColumn(0).setResizable(false);
            tblDisplayStrings.getColumnModel().getColumn(0).setPreferredWidth(140);
            tblDisplayStrings.getColumnModel().getColumn(1).setResizable(false);
            tblDisplayStrings.getColumnModel().getColumn(2).setResizable(false);
            tblDisplayStrings.getColumnModel().getColumn(3).setResizable(false);
            tblDisplayStrings.getColumnModel().getColumn(4).setResizable(false);
            tblDisplayStrings.getColumnModel().getColumn(5).setResizable(false);
        }

        pnlHeading.setBackground(new java.awt.Color(0, 102, 153));

        lblStringsAdminPage.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblStringsAdminPage.setForeground(new java.awt.Color(239, 128, 47));
        lblStringsAdminPage.setText("Strings Admin Page");

        lblMinimize.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        lblMinimize.setForeground(new java.awt.Color(255, 255, 255));
        lblMinimize.setText("-");
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
        });

        lblExit.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblExit.setForeground(new java.awt.Color(255, 255, 255));
        lblExit.setText("x");
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlHeadingLayout = new javax.swing.GroupLayout(pnlHeading);
        pnlHeading.setLayout(pnlHeadingLayout);
        pnlHeadingLayout.setHorizontalGroup(
            pnlHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeadingLayout.createSequentialGroup()
                .addGap(721, 721, 721)
                .addComponent(lblStringsAdminPage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlHeadingLayout.setVerticalGroup(
            pnlHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeadingLayout.createSequentialGroup()
                .addGroup(pnlHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlHeadingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStringsAdminPage, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        lblSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSearch.setText("Search for Strings");

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
        });

        txtName.setPreferredSize(new java.awt.Dimension(100, 25));

        txtStringComp.setPreferredSize(new java.awt.Dimension(100, 25));

        txtStringCol.setPreferredSize(new java.awt.Dimension(100, 25));

        txtStringGuage.setPreferredSize(new java.awt.Dimension(100, 25));

        txtStock.setPreferredSize(new java.awt.Dimension(100, 25));

        txtStringPrice.setPreferredSize(new java.awt.Dimension(100, 25));

        lblStringName.setText("String Name");

        lblStringComp.setText("String Composition");

        lblStringColour.setText("String colour");

        lblStringGuage.setText("String Guage");

        lblStringPrice.setText("String Price(Rands)");

        lblstock.setText("Available Stock");

        lblEnterUpdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEnterUpdate.setForeground(new java.awt.Color(51, 0, 255));
        lblEnterUpdate.setText("Enter New values to update Selected field");

        btnUpdate.setText("Update");
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });

        btnDelete.setText("Delete Selected Record");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });

        btnNewRecord.setText("Create New Record");
        btnNewRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewRecordMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(372, 372, 372)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblStringName)
                                .addGap(98, 98, 98))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStringComp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStringComp))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStringColour)
                            .addComponent(txtStringCol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStringGuage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStringGuage))
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStringPrice)
                            .addComponent(txtStringPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblstock)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(btnDelete)
                        .addGap(500, 500, 500)
                        .addComponent(lblEnterUpdate))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSearch)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75)
                        .addComponent(scrDisplayRackets, javax.swing.GroupLayout.PREFERRED_SIZE, 1569, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(785, 785, 785)
                        .addComponent(btnUpdate)
                        .addGap(41, 41, 41)
                        .addComponent(btnNewRecord)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlHeading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSearch)
                                .addGap(18, 18, 18)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(scrDisplayRackets, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE))
                        .addGap(58, 58, 58)
                        .addComponent(lblEnterUpdate)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDelete)
                        .addGap(47, 47, 47)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStringName)
                    .addComponent(lblStringComp)
                    .addComponent(lblStringColour)
                    .addComponent(lblStringGuage)
                    .addComponent(lblStringPrice)
                    .addComponent(lblstock))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStringComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStringCol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStringGuage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStringPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnNewRecord))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        this.setState(JFrame.ICONIFIED);//minimizes the screen
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked

        this.dispose();
    }//GEN-LAST:event_lblExitMouseClicked

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
              String search = txtSearch.getText();
        //making the variable equal to the text/search that was entered by the user
      //where result is like the help type entered by user

        DefaultTableModel model = (DefaultTableModel) tblDisplayStrings.getModel();
        model.setRowCount(0);

        dbObjTennis.showStringsSearch(tblDisplayStrings, search);//displaying search inside the table that was created to display the reuslts of the search
    }//GEN-LAST:event_txtSearchKeyPressed

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
DefaultTableModel model = (DefaultTableModel) tblDisplayStrings.getModel();
        int columnString = 0;
        int columnColour = 2;
        int row = tblDisplayStrings.getSelectedRow();
        String tempOrderString = tblDisplayStrings.getModel().getValueAt(row, columnString).toString();
      String tempOrderColour = tblDisplayStrings.getModel().getValueAt(row, columnColour).toString();
        

        
        
      String name = txtName.getText();
String comp = txtStringComp.getText();
String colour = txtStringCol.getText();
double gauge  = Double.parseDouble(txtStringGuage.getText());
int price = Integer.parseInt(txtStringPrice.getText());
int stock = Integer.parseInt(txtStock.getText());
 
//updating where the ID is what they entered the ID to be 
     try{//try catch here in order to try and catch the SQLExcepption error
         dbObjTennis.updateString(tempOrderString, tempOrderColour, name, comp, colour, gauge, price, stock);//this is used to update the record
         JOptionPane.showMessageDialog(null, "Item has been successfully updated!");
         model.setRowCount(0);
         DefaultTableModel modelRefreshed = (DefaultTableModel) tblDisplayStrings.getModel();
         dbObjTennis.showStringsAlphabetical(tblDisplayStrings);
     }catch (SQLException e) {
         JOptionPane.showMessageDialog(null, "Cannot insert record\n " +e);
         
     }

    }//GEN-LAST:event_btnUpdateMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
      DefaultTableModel model = (DefaultTableModel) tblDisplayStrings.getModel();
        int columnString = 0;
        int columnColour= 2;
        int row = tblDisplayStrings.getSelectedRow();

        String tempOrder = tblDisplayStrings.getModel().getValueAt(row, columnString).toString();
        String tempOrderColour = tblDisplayStrings.getModel().getValueAt(row, columnColour).toString();
        
        //updating where the ID is what they entered the ID to be 
     try{//try catch here in order to try and catch the SQLExcepption error
         dbObjTennis.deleteString(tempOrder, tempOrderColour);//this is used to update the record
         JOptionPane.showMessageDialog(null, "Item has been successfully removed!");
         model.setRowCount(0);
         DefaultTableModel modelRefreshed = (DefaultTableModel) tblDisplayStrings.getModel();
         dbObjTennis.showStringsAlphabetical(tblDisplayStrings);
     }catch (SQLException e) {
         JOptionPane.showMessageDialog(null, "Record was not deleted " +e);
         
     }
// TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnNewRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewRecordMouseClicked
       DefaultTableModel model = (DefaultTableModel) tblDisplayStrings.getModel();
  
      String name = txtName.getText();
String comp = txtStringComp.getText();
String colour = txtStringCol.getText();
double gauge  = Double.parseDouble(txtStringGuage.getText());
int price = Integer.parseInt(txtStringPrice.getText());
int stock = Integer.parseInt(txtStock.getText());
 
//updating where the ID is what they entered the ID to be 
     try{//try catch here in order to try and catch the SQLExcepption error
         dbObjTennis.insertString(name, comp, colour, gauge, price, stock);//this is used to update the record
         JOptionPane.showMessageDialog(null, "New record has successfully been added to the database!");
         model.setRowCount(0);
         DefaultTableModel modelRefreshed = (DefaultTableModel) tblDisplayStrings.getModel();
         dbObjTennis.showStringsAlphabetical(tblDisplayStrings);
         
     }catch (SQLException e) {
         JOptionPane.showMessageDialog(null, "Cannot insert record\n " +e);
         
     }
    }//GEN-LAST:event_btnNewRecordMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNewRecord;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblEnterUpdate;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblStringColour;
    private javax.swing.JLabel lblStringComp;
    private javax.swing.JLabel lblStringGuage;
    private javax.swing.JLabel lblStringName;
    private javax.swing.JLabel lblStringPrice;
    private javax.swing.JLabel lblStringsAdminPage;
    private javax.swing.JLabel lblstock;
    private javax.swing.JPanel pnlHeading;
    private javax.swing.JScrollPane scrDisplayRackets;
    private javax.swing.JTable tblDisplayStrings;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtStringCol;
    private javax.swing.JTextField txtStringComp;
    private javax.swing.JTextField txtStringGuage;
    private javax.swing.JTextField txtStringPrice;
    // End of variables declaration//GEN-END:variables
}
