/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Dimension;
import java.sql.SQLException;

import javax.swing.JOptionPane;
/**
 *
 * @author 21nic
 */
public class ThanksForShopping extends javax.swing.JFrame {

    /**
     * Creates new form ThanksForShopping
     */
    private String email;
    private String password; 
    public TennisAlliance dbObjTennis;
    public ThanksForShopping(String email, String password) {
        this.password = password; 
        this.email = email;
        initComponents();
         dbObjTennis = new TennisAlliance(email);
        this.setMinimumSize(new Dimension(1497, 799));
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeading = new javax.swing.JLabel();
        btnProceed = new javax.swing.JButton();
        scrFinalMsg = new javax.swing.JScrollPane();
        txaFinalMsg = new javax.swing.JTextArea();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblHeading.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        lblHeading.setForeground(new java.awt.Color(255, 102, 102));
        lblHeading.setText("Thank you for shopping with Tennis Alliance");
        getContentPane().add(lblHeading);
        lblHeading.setBounds(108, 46, 1334, 73);

        btnProceed.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnProceed.setText("Proceed");
        btnProceed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProceedMouseClicked(evt);
            }
        });
        getContentPane().add(btnProceed);
        btnProceed.setBounds(1255, 690, 180, 70);

        txaFinalMsg.setEditable(false);
        txaFinalMsg.setBackground(new java.awt.Color(0, 0, 0));
        txaFinalMsg.setColumns(20);
        txaFinalMsg.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        txaFinalMsg.setForeground(new java.awt.Color(255, 255, 255));
        txaFinalMsg.setRows(5);
        txaFinalMsg.setText("\nYour order was successful! We will process your \norder once confirmation of payment has been \nreceived to tennis@alliance.co.za\n\nCash On Delivery Option will be confirmed once\npayment confirmation has been received\n\nIn the meantime, we have reset your basket. \nPlease feel free to continue shopping! ");
        scrFinalMsg.setViewportView(txaFinalMsg);

        getContentPane().add(scrFinalMsg);
        scrFinalMsg.setBounds(870, 180, 540, 280);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesForPAT/end.jpg"))); // NOI18N
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 0, 1500, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProceedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProceedMouseClicked

        this.dispose();
      
        new MainPage(email, password).setVisible(true);   
          try {
            dbObjTennis.deleteUserCart(email);
           
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnProceedMouseClicked

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProceed;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JScrollPane scrFinalMsg;
    private javax.swing.JTextArea txaFinalMsg;
    // End of variables declaration//GEN-END:variables
}
